### ISSUE TITLE
类型转换错误

### ISSUE THREAD

**Issue by WJHXD1B** [LLOneBot/LLOneBot#121]
QQ版本：9.9.7-21804

LLOneBot版本：3.13.5

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：OverFlow

BUG描述：时不时控制台报错

复现步骤：正常运行

LLOneBot日志:
<img width="992" alt="ll" src="https://github.com/LLOneBot/LLOneBot/assets/79585033/747eeb54-5604-4f95-93a8-0248bad4ddb5">

2024-03-08 22:39:36 W/stderr: Exception in thread "DefaultDispatcher-worker-9" java.lang.NumberFormatException: For input string: "7344002220917200861"
2024-03-08 22:39:36 W/stderr:   at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
2024-03-08 22:39:36 W/stderr:   at java.base/java.lang.Integer.parseInt(Integer.java:668)
2024-03-08 22:39:36 W/stderr:   at java.base/java.lang.Integer.parseInt(Integer.java:784)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:219)
2024-03-08 22:39:36 W/stderr:   at cn.evole.onebot.sdk.util.json.MsgAdapter.deserialize(MsgAdapter.java:15)
2024-03-08 22:39:36 W/stderr:   at cn.evole.onebot.sdk.util.json.MsgAdapter.deserialize(MsgAdapter.java:8)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.Gson.fromJson(Gson.java:1227)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.Gson.fromJson(Gson.java:1137)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.Gson.fromJson(Gson.java:1047)
2024-03-08 22:39:36 W/stderr:   at top.mrxiaom.overflow.internal.deps.gson.Gson.fromJson(Gson.java:1014)
2024-03-08 22:39:36 W/stderr:   at cn.evole.onebot.sdk.util.json.GsonUtil.fromJson(GsonUtil.java:83)
2024-03-08 22:39:36 W/stderr:   at cn.evolvefield.onebot.client.core.Bot.getMsg(Bot.kt:288)
2024-03-08 22:39:36 W/stderr:   at cn.evolvefield.onebot.client.core.Bot$getMsg$1.invokeSuspend(Bot.kt)
2024-03-08 22:39:36 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-03-08 22:39:36 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-03-08 22:39:36 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-03-08 22:39:36 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@5ca3b2ba, Dispatchers.Default]

**Comment by linyuchen** [comment]
似乎是overflow那边把`real_id`解析了，这玩意儿onebot11没有的，不需要解析，建议移步到overflow项目提问

**Comment by MrXiaoM** [comment]
> 似乎是overflow那边把`real_id`解析了，这玩意儿onebot11没有的，不需要解析，建议移步到overflow项目提问

群友的 Issue 可能没说清楚。
出现这个问题的原因是，Onebot 11 标准的 message_id 类型是 int32，而 LLOnebot 给出的 message_id 范围已经超出 int32 了，导致无法解析。

**Comment by linyuchen** [comment]
> > 似乎是overflow那边把`real_id`解析了，这玩意儿onebot11没有的，不需要解析，建议移步到overflow项目提问
> 
> 
> 
> 群友的 Issue 可能没说清楚。
> 
> 出现这个问题的原因是，Onebot 11 标准的 message_id 类型是 int32，而 LLOnebot 给出的 message_id 范围已经超出 int32 了，导致无法解析。

现在的llonebot版本都是int32的message_id了，看他提供的日志，只有real_id这个字段是这样的

**Comment by MrXiaoM** [comment]
> 现在的llonebot版本都是int32的message_id了，看他提供的日志，只有real_id这个字段是这样的

但是…现版本的 Overflow，以及上游项目 onebot-sdk，消息事件里面都没有 real_id

**Comment by linyuchen** [comment]
> > 现在的llonebot版本都是int32的message_id了，看他提供的日志，只有real_id这个字段是这样的
> 
> ~~但是…现版本的 Overflow，以及上游项目 onebot-sdk，消息事件里面都没有 real_id~~ MsgAdapter 那没事了
> 
> 不对啊，MsgAdapter 解析的是 get_msg 的回应，Onebot 11 标准里有 real_id，类型是 int32

那知道是什么问题了，我这边改一下

**Comment by WJHXD1B** [comment]
麻烦两位大佬了

**Comment by linyuchen** [comment]
[v3.13.10](https://github.com/LLOneBot/LLOneBot/releases)已修正`real_id`类型
