### ISSUE TITLE
[Feature]希望未来能支持获取群聊记录

### ISSUE THREAD

**Issue by ElaineOwO** [LLOneBot/LLOneBot#128]
首先感谢作者的插件，让小白的bot能重获生机——
在此有一个小小的请求
在使用[[TRSS-Yunzai]](https://github.com/TimeRainStarSky/Yunzai)并安装[chatgpt-plugin](https://github.com/ikechan8370/chatgpt-pluginl)后，获取群聊记录时会报错提示
`TypeError: e.group.getChatHistory is not a function
    at getChatHistoryGroup (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/utils/chat.js:8:35)
    at chatgpt.sendMessage (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/model/core.js:202:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.abstractChat (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:794:25)
    at async chatgpt (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:559:5)
    at async PluginsLoader.deal (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/lib/plugins/loader.js:262:41)`
希望未来能加入获取群聊记录的功能QuQ
最后祝大佬生活愉快

**Comment by linyuchen** [comment]
v3.17.0已支持

**Comment by ElaineOwO** [comment]
> v3.17.0已支持

感谢大佬
