### ISSUE TITLE
guild-member-added 炸了

### ISSUE THREAD

**Issue by hutuyee** [LLOneBot/LLOneBot#131]
QQ版本：
版本: 9.9.7-21804 (64位)
LLOneBot版本：
3.15.0
调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：
Koishi
BUG描述：
![13484c59d874ade375b95da3958ad2c6](https://github.com/LLOneBot/LLOneBot/assets/110071800/9f42e52b-37e5-4a92-be11-081c1c7e1bcc)
Koishi报错:
2024-03-15 22:01:58 [W] market Error: getaddrinfo EAI_AGAIN registry.koishi.chat
                            at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
2024-03-15 22:01:58 [W] market TypeError: fetch failed
                            at Object.fetch (node:internal/deps/undici/undici:11576:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:198:19)
                            at async Proxy.<anonymous> (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:72:26)
                            at async _MarketProvider.collect (D:\DS\bot\cnm\node_modules\@koishijs\plugin-market\lib\node\index.js:391:22)
2024-03-15 22:01:58 [W] market Error: fetch https://registry.koishi.chat/index.json failed
                            at D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:201:23
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:198:19)
                            at async Proxy.<anonymous> (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:72:26)
                            at async _MarketProvider.collect (D:\DS\bot\cnm\node_modules\@koishijs\plugin-market\lib\node\index.js:391:22)
2024-03-15 22:01:58 [W] market Error: getaddrinfo EAI_AGAIN registry.koishi.chat
                            at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
2024-03-15 22:01:58 [W] market TypeError: fetch failed
                            at Object.fetch (node:internal/deps/undici/undici:11576:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:198:19)
                            at async Proxy.<anonymous> (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:72:26)
                            at async _MarketProvider.collect (D:\DS\bot\cnm\node_modules\@koishijs\plugin-market\lib\node\index.js:391:22)
2024-03-15 22:01:58 [W] market Error: fetch https://registry.koishi.chat/index.json failed
                            at D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:201:23
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:198:19)
                            at async Proxy.<anonymous> (D:\DS\bot\cnm\node_modules\@satorijs\core\node_modules\undios\lib\index.cjs:72:26)
                            at async _MarketProvider.collect (D:\DS\bot\cnm\node_modules\@koishijs\plugin-market\lib\node\index.js:391:22)
2024-03-15 22:02:02 [W] market request timeout

**Comment by linyuchen** [comment]
v3.15.1已修复
