### ISSUE TITLE
还是无法获取群聊记录

### ISSUE THREAD

**Issue by ElaineOwO** [LLOneBot/LLOneBot#146]
QQ版本：9.9.7-21804

LLOneBot版本：3.17.0

调用LLOneBot的方式或者应用端(如postman直接调用，或NoneBot2、Koishi)：TRSS崽

BUG描述：使用[chatgpt-plugin](https://github.com/ikechan8370/chatgpt-plugin) 时仍然无法获取群聊记录

LLOneBot日志:
```
[TRSSYz][15:31:09.252][INFO] [940983440 <= 759330212, 992073203] 群消息：[叭卟啵哔, Elaine] #chat 你能看到群里说了什么码
[TRSSYz][15:31:09.462][INFO] chatgpt prompt: 你能看到群里说了什么码
[TRSSYz][15:31:09.538][DEBU] [ws://localhost:2536/OneBotv11 => ::1:50649-XqsRAxFyDr/wt46SXEKTZg==] 消息 {"action":"get_group_msg_history","params":{"group_id":759330212,"message_seq":0,"count":1},"echo":"da0d6aca-782a-413d-a2d6-e1526ca08de4"}
[TRSSYz][15:31:09.542][DEBU] [ws://localhost:2536/OneBotv11 <= ::1:50649-XqsRAxFyDr/wt46SXEKTZg==] 消息 {"status":"failed","retcode":1200,"data":null,"message":"TypeError: Cannot read properties of undefined (reading 'map')\n    at GoCQHTTPGetGroupMsgHistory._handle (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:65106:31)\n    at async GoCQHTTPGetGroupMsgHistory.websocketHandle (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:28380:23)\n    at async ReverseWebsocket.onmessage (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:64864:26)\n    at async WebSocket.<anonymous> (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:64906:7)","wording":"TypeError: Cannot read properties of undefined (reading 'map')\n    at GoCQHTTPGetGroupMsgHistory._handle (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:65106:31)\n    at async GoCQHTTPGetGroupMsgHistory.websocketHandle (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:28380:23)\n    at async ReverseWebsocket.onmessage (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:64864:26)\n    at async WebSocket.<anonymous> (C:\\Program Files\\Tencent\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:64906:7)","echo":"da0d6aca-782a-413d-a2d6-e1526ca08de4"}
[TRSSYz][15:31:09.542][WARN] 获取群聊聊天记录失败，本次对话不携带聊天记录 TypeError: Cannot read properties of undefined (reading 'length')
    at getChatHistoryGroup (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/utils/chat.js:9:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async chatgpt.sendMessage (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/model/core.js:202:27)
    at async chatgpt.abstractChat (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:794:25)
    at async chatgpt (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/plugins/chatgpt-plugin/apps/chat.js:559:5)
    at async PluginsLoader.deal (file:///C:/Users/BOT/Desktop/BOT/Miao-Yunzai/lib/plugins/loader.js:254:41)
```
帮帮忙叭我什么都会做的（磕头

**Comment by linyuchen** [comment]
v3.18.1 fixed
