### ISSUE TITLE
[BUG] linux下使用llonebot-docker无法正常选择ffmpeg

### ISSUE THREAD

**Issue by viodnomad** [LLOneBot/LLOneBot#182]
### 系统版本

Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-47-generic x86_64)

### QQNT 版本

9.9.7-21217

### LLOneBot 版本

3.22.0

### OneBot 客户端

Koishi v4.17.3

### 发生了什么?

无法正常选择ffmpeg
![image](https://github.com/LLOneBot/LLOneBot/assets/111840192/cc13c43f-b787-4621-9921-854b647a4230)

### 如何复现

1.apt install ffmpeg
2.bash <(curl -s -L https://cdn.jsdelivr.net/gh/MliKiowa/llonebot-docker/fastboot.sh)
3.访问http://你的docker-ip:6099/plugin/LLOneBot/iframe.html 选择ffmpeg

### 期望的结果?

正常发送语音

### LLOneBot 运行日志

```shell
4/8/2024, 8:06:13 AM MIO(1807833503): 收到反向Websocket消息 {"action":"send_group_msg","params":{"group_id":群,"message":[{"type":"record","data":{"file":"http://m8.music.126.net/20240408162950/679526f371a484c54bd4e4a423116a63/ymusic/ef36/0e48/fbd4/9e63524dd9674a5c96010de205fd520d.mp3","cache":0}}]},"echo":1914} 

4/8/2024, 8:06:13 AM MIO(1807833503): 获取文件类型 mp3 /opt/QQ/resources/app/LiteLoader/data/LLOneBot/temp/1da0ecca-5ac6-4aaf-b37c-b990cc2432dd9e63524dd9674a5c96010de205fd520d.mp3 

4/8/2024, 8:06:13 AM MIO(1807833503): 语音文件/opt/QQ/resources/app/LiteLoader/data/LLOneBot/temp/1da0ecca-5ac6-4aaf-b37c-b990cc2432dd9e63524dd9674a5c96010de205fd520d.mp3.mp3需要转换成silk 

4/8/2024, 8:06:13 AM MIO(1807833503): FFmpeg处理转换出错:  spawn F:/Web/ffmpeg.exe ENOENT 

4/8/2024, 8:06:13 AM MIO(1807833503): convert silk failed Error: spawn F:/Web/ffmpeg.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) 

4/8/2024, 8:06:13 AM MIO(1807833503): 发生错误 {"code":"ERR_INVALID_ARG_TYPE"}
```

### OneBot 客户端运行日志

```shell
2024-04-08 16:04:51 [W] session Error: Error with request send_private_msg, args: {"user_id":3088023648,"message":[{"type":"record","data":{"file":"http://m8.music.126.net/20240408162950/679526f371a484c54bd4e4a423116a63/ymusic/ef36/0e48/fbd4/9e63524dd9674a5c96010de205fd520d.mp3","cache":0}}]}, retcode: 1200
                            at Internal._get (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/types.js:44:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Internal.<computed> [as sendPrivateMsg] (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/types.js:84:26)
                            at async OneBotMessageEncoder.flush (/koishi/node_modules/koishi-plugin-adapter-onebot/lib/bot/message.js:94:24)
                            at async OneBotMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:561:5)
                            at async OneBotBot.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:326:22)
                            at async Command.<anonymous> (/koishi/node_modules/koishi-plugin-music-downloadvoice-api/lib/index.js:205:17)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1137:14)
                            at async Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1151:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2170:22
```

**Comment by MliKiowa** [comment]
草 别点那个设置按钮啊

**Comment by viodnomad** [comment]
好
