### ISSUE TITLE
[BUG] 发送消息失败

### ISSUE THREAD

**Issue by HanamiSeishin** [LLOneBot/LLOneBot#183]
### 系统版本

winserver 2016 standard

### QQNT 版本

9.9.9-22741

### LLOneBot 版本

3.22.0

### OneBot 客户端

nonebot v11

### 发生了什么?

nonebot_plugin_fortune插件发送消息执行报错
![image](https://github.com/LLOneBot/LLOneBot/assets/83294751/ef98332e-f1df-4e4e-8815-c4b63d28a1ba)

### 如何复现

1.winserver 2016 standard系统启动qqnt
2.centos7系统启动nonebot并使用v11适配器开启反向socket监听
3.发送”今日运势“触发nonebot_plugin_fortune插件逻辑，报告发送消息失败并返回错误信息

经过实验，使用反向socket或者正向socket都会出现问题

其他大部分插件能够正常工作，当前只有该插件会导致该错误
![image](https://github.com/LLOneBot/LLOneBot/assets/83294751/c585dbd9-ac15-4b13-9c63-04a8c0ff3761)

删除消息中的”✨“后仍然报错

### 期望的结果?

![image](https://github.com/LLOneBot/LLOneBot/assets/83294751/d646a92b-cdd5-4286-88c8-1051c21ee503)

### LLOneBot 运行日志

```shell
【较多乱码】

         msg_short_id_-2147483590"7355577097781904075"鏍??         msg_id_7355577097781904075?"{\"msgId\":\"7355577097781904075\",\"msgRandom\":\"1119886519\",\"msgSeq\":\"5709\",\"cntSeq\":\"0\",\"chatType\":2,\"msgType\":2,\"subMsgType\":1,\"sendType\":0,\"senderUid\":\"u_gQygTmpW0BcyMEpqCyAhtg\",\"peerUid\":\"778011202\",\"channelId\":\"\",\"guildId\":\"\",\"guildCode\":\"0\",\"fromUid\":\"0\",\"fromAppid\":\"0\",\"msgTime\":\"1712603750\",\"msgMeta\":\"0x\",\"sendStatus\":2,\"sendRemarkName\":\"\",\"sendMemberName\":\"\",\"sendNickName\":\"闆€缈庢ⅵ\",\"guildName\":\"\",\"channelName\":\"\",\"elements\":[{\"elementType\":1,\"elementId\":\"7355577097781904074\",\"extBufForUI\":\"0x\",\"textElement\":{\"content\":\"浠婃棩杩愬娍\",\"atType\":0,\"atUid\":\"0\",\"atTinyId\":\"0\",\"atNtUid\":\"\",\"subElementType\":0,\"atChannelId\":\"0\",\"linkInfo\":null,\"atRoleId\":\"0\",\"atRoleColor\":0,\"atRoleName\":\"\",\"needNotify\":0},\"faceElement\":null,\"marketFaceElement\":null,\"replyElement\":null,\"picElement\":null,\"pttElement\":null,\"videoElement\":null,\"grayTipElement\":null,\"arkElement\":null,\"fileElement\":null,\"liveGiftElement\":null,\"markdownElement\":null,\"structLongMsgElement\":null,\"multiForwardMsgElement\":null,\"giphyElement\":null,\"walletElement\":null,\"inlineKeyboardElement\":null,\"textGiftElement\":null,\"calendarElement\":null,\"yoloGameResultElement\":null,\"avRecordElement\":null,\"structMsgElement\":null,\"faceBubbleElement\":null,\"shareLocationElement\":null,\"tofuRecordElement\":null,\"taskTopMsgElement\":null,\"recommendedMsgElement\":null,\"actionBarElement\":null}],\"records\":[],\"emojiLikesList\":[],\"commentCnt\":\"0\",\"directMsgFlag\":0,\"directMsgMembers\":[],\"peerName\":\"鏂囦欢淇濆瓨\",\"freqLimitInfo\":null,\"editable\":false,\"avatarMeta\":\"\",\"avatarPendant\":\"\",\"feedId\":\"\",\"roleId\":\"0\",\"timeStamp\":\"0\",\"clientIdentityInfo\":null,\"isImportMsg\":false,\"atType\":0,\"roleType\":0,\"fromChannelRoleInfo\":{\"roleId\":\"0\",\"name\":\"\",\"color\":0},\"fromGuildRoleInfo\":{\"roleId\":\"0\",\"name\":\"\",\"color\":0},\"levelRoleInfo\":{\"roleId\":\"0\",\"name\":\"\",\"color\":0},\"recallTime\":\"0\",\"isOnlineMsg\":true,\"generalFlags\":\"0x\",\"clientSeq\":\"0\",\"fileGroupSize\":null,\"foldingInfo\":null,\"multiTransInfo\":null,\"senderUin\":\"737295724\",\"peerUin\":\"778011202\",\"msgAttrs\":{},\"anonymousExtInfo\":null,\"nameType\":0,\"avatarFlag\":0,\"extInfoForUI\":null,\"personalMedal\":null,\"categoryManage\":0,\"msgEventInfo\":null,\"msgShortId\":-2147483590}"i]3          msg_seq_id_5709"7355577097781904075"
```

### OneBot 客户端运行日志

```shell
【部分乱码】

04-09 03:15:51 [INFO] nonebot_plugin_fortune | User 737295724 | Group 778011202 åckages/nonebot/__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/usr/local/python3/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/python3/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/python3/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/usr/local/python3/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/March7th/plugins/nonebot_plugin_fortune/__init__.py", line 101, in _
    await general_divine.finish(msg, at_sender=True)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 574, in finish
    await cls.send(message, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 558, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "/usr/local/python3/lib/python3.10/site-packages/nonebot/adapters/onebot/v11/utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message="TypeError: Cannot read properties of undefined (reading 'toString')\n    at SendMsgElementConstructor.pic (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:27432:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async createSendElements (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:27996:35)\n    at async SendMsg._handle (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:28135:52)\n    at async SendMsg.websocketHandle (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:27708:23)\n    at async OB11WebsocketServer.handleAction (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:65678:26)", wording="TypeError: Cannot read properties of undefined (reading 'toString')\n    at SendMsgElementConstructor.pic (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:27432:26)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async createSendElements (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:27996:35)\n    at async SendMsg._handle (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:28135:52)\n    at async SendMsg.websocketHandle (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:27708:23)\n    at async OB11WebsocketServer.handleAction (D:\\program\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:65678:26)", echo='6')
```

**Comment by linyuchen** [comment]
给的llonebot日志不对，日志是位于logs文件夹，如果为空需要在llonebot设置中开启写入日志

**Comment by HanamiSeishin** [comment]
[logs.zip](https://github.com/LLOneBot/LLOneBot/files/14913353/logs.zip)

**Comment by HanamiSeishin** [comment]
> 给的llonebot日志不对，日志是位于logs文件夹，如果为空需要在llonebot设置中开启写入日志

已上传日志文件

**Comment by linyuchen** [comment]
你的nb和llonebot不在同个系统内，nb提交的是本地路径，llonebot是找不到的，需要修改插件发送图片方式为base64

**Comment by HMScygnet** [comment]
我也遇到了同样问题，如果使用base64发png图片，NTQQ在本地会把图片转为jpg格式，如果前面加上data:image/png;会被识别成路径，必须在发图前把图片转为jpg格式

**Comment by HanamiSeishin** [comment]
问题已解决

**Comment by HanamiSeishin** [comment]
> 问题已解决

from io import BytesIO
from PIL import Image

img: Image.Image = Image.open(image_file)
buf = BytesIO()
img.save(buf, format='png')

MessageSegment.image(buf)
