### ISSUE TITLE
不能发送临时消息

### ISSUE THREAD

**Issue by niusme** [LLOneBot/LLOneBot#203]
部署方案：
bash <(curl -s -L https://cdn.jsdelivr.net/gh/MliKiowa/llonebot-docker/fastboot.sh)

执行请求：
curl:
curl --request POST \
  --url http://14.***.***.206:3000/send_private_msg \
  --header 'content-type: application/json' \
  --data '{
    "user_id": 17****227,
    "message": "早上好",
    "auto_escape": true
}'

响应结果:
{
	"status": "failed",
	"retcode": 400,
	"data": null,
	"message": "不能发送临时消息",
	"wording": "不能发送临时消息",
	"echo": null
}

我能确保双方均添加为好友。

**Comment by idranme** [comment]
v3.27.4 是否依然存在该问题？

**Comment by Fortern** [comment]
v3.28.0 依然存在该问题

**Comment by Fortern** [comment]
附带错误日志
```
2024/8/9 11:33:36 墨酱(2077******): 收到http请求 /send_private_msg {"user_id":1007******,"message":"简单的消息","auto_escape":true} 

2024/8/9 11:33:36 墨酱(2077******): hook error {} *****

2024/8/9 11:33:36 墨酱(2077******): 刷新好友列表失败 TypeError: i.data is not iterable
    at ri.getFriends (C:\Users\Mi\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:584)
    at async Pa (C:\Users\Mi\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:75790)
    at async $4.check (C:\Users\Mi\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:58832)
    at async $4.handle (C:\Users\Mi\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:50929)
    at async C:\Users\Mi\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:346:4673 

2024/8/9 11:33:36 墨酱(2077******): hook error {} *****

2024/8/9 11:33:36 墨酱(2077******): nodeIKernelBuddyService/getBuddyList callback {"result":0,"errMsg":"success"} 

```

**Comment by idranme** [comment]
v3.28.3 是否依然存在该问题？

**Comment by Fortern** [comment]
问题已解决
