### ISSUE TITLE
[BUG] 群与私聊接收到的合并转发消息报错

### ISSUE THREAD

**Issue by YuLinLoli** [LLOneBot/LLOneBot#215]
### 系统版本

Windows Server 2022 Datacenter 21H2

### QQNT 版本

9.9.9-23159 (64位)

### LLOneBot 版本

3.24.3

### OneBot 客户端

overflow-core-all-2.16.0-f4dfdfe-SNAPSHOT

### 发生了什么?

**### 群内**
2024-05-13 11:28:51 W/Onebot: Request failed: [get_forward_msg] app=LLOneBot v3.24.3, message=Error: msg not found
    at GoCQHTTGetForwardMsgAction._handle (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78395:13)
    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:29550:23)
    at async ReverseWebsocket.onmessage (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78120:26)
    at async WebSocket.<anonymous> (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78163:7), retJson={"status":"failed","retcode":1200,"data":null,"message":"Error: msg not found\n    at GoCQHTTGetForwardMsgAction._handle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78395:13)\n    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:29550:23)\n    at async ReverseWebsocket.onmessage (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78120:26)\n    at async WebSocket.<anonymous> (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78163:7)","wording":"Error: msg not found\n    at GoCQHTTGetForwardMsgAction._handle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78395:13)\n    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:29550:23)\n    at async ReverseWebsocket.onmessage (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78120:26)\n    at async WebSocket.<anonymous> (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78163:7)","echo":112}
2024-05-13 11:28:51 W/Overflow: 解析消息 forward{"id":"7368321043502730469"} 时出现错误 (llonebot 3.24.3)
java.lang.NullPointerException: Cannot read field "message" because "data" is null
	at top.mrxiaom.overflow.internal.Overflow.downloadForwardMessage(Overflow.kt:363)
	at top.mrxiaom.overflow.internal.Overflow$downloadForwardMessage$1.invokeSuspend(Overflow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
**### 私聊**
2024-05-13 12:15:35 W/Onebot: Request failed: [get_forward_msg] app=LLOneBot v3.24.3, message=Error: msg not found
    at GoCQHTTGetForwardMsgAction._handle (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78395:13)
    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:29550:23)
    at async ReverseWebsocket.onmessage (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78120:26)
    at async WebSocket.<anonymous> (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78163:7), retJson={"status":"failed","retcode":1200,"data":null,"message":"Error: msg not found\n    at GoCQHTTGetForwardMsgAction._handle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78395:13)\n    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:29550:23)\n    at async ReverseWebsocket.onmessage (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78120:26)\n    at async WebSocket.<anonymous> (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78163:7)","wording":"Error: msg not found\n    at GoCQHTTGetForwardMsgAction._handle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78395:13)\n    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:29550:23)\n    at async ReverseWebsocket.onmessage (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78120:26)\n    at async WebSocket.<anonymous> (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78163:7)","echo":21}

### 如何复现

群内或者私聊出现合并转发消息时机器人报错

### 期望的结果?

正常解析合并转发消息

### LLOneBot 运行日志

```shell
2024-05-13 12:15:27 W/Onebot: Request failed: [get_forward_msg] app=LLOneBot v3.24.3, message=Error: msg not found
    at GoCQHTTGetForwardMsgAction._handle (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78395:13)
    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:29550:23)
    at async ReverseWebsocket.onmessage (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78120:26)
    at async WebSocket.<anonymous> (D:\QQNT\resources\app\LiteLoaderQQNT-main\plugins\LLOneBot\main\main.cjs:78163:7), retJson={"status":"failed","retcode":1200,"data":null,"message":"Error: msg not found\n    at GoCQHTTGetForwardMsgAction._handle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78395:13)\n    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:29550:23)\n    at async ReverseWebsocket.onmessage (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78120:26)\n    at async WebSocket.<anonymous> (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78163:7)","wording":"Error: msg not found\n    at GoCQHTTGetForwardMsgAction._handle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78395:13)\n    at async GoCQHTTGetForwardMsgAction.websocketHandle (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:29550:23)\n    at async ReverseWebsocket.onmessage (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78120:26)\n    at async WebSocket.<anonymous> (D:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:78163:7)","echo":20}
```

### OneBot 客户端运行日志

```shell
2024-05-13 12:15:27 W/Overflow: 解析消息 forward{"id":"7368333053450819149"} 时出现错误 (llonebot 3.24.3)
java.lang.NullPointerException: Cannot read field "message" because "data" is null
        at top.mrxiaom.overflow.internal.Overflow.downloadForwardMessage(Overflow.kt:363)
        at top.mrxiaom.overflow.internal.Overflow$downloadForwardMessage$1.invokeSuspend(Overflow.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by linyuchen** [comment]
看一下LLOneBot的日志

**Comment by MliKiowa** [comment]
拿的id是错的应该拿短id

**Comment by MliKiowa** [comment]
{"action":"get_forward_msg","params":{"id":"7370356768927433236"},"echo":3625}
这个id应该是message_id

**Comment by linyuchen** [comment]
3.26.1已修复
