### ISSUE TITLE
连接nonebot后无法正常发送消息

### ISSUE THREAD

**Issue by A-n-k-a** [LLOneBot/LLOneBot#252]
### 系统版本

Windows Server 2022 21H2

### QQNT 版本

9.9.11-24402

### LLOneBot 版本

3.26.5

### OneBot 客户端

nonebot 2.3.1

### 发生了什么?

正向ws和反向ws均尝试过连接，且现象相同：
nonebot不安装任何插件时，在运行日志中看到所有消息接收均正常，一旦安装了插件且消息触发了插件回复就会报错“发送超时”，但实际上，当消息是文本且文本字数较少时能够在QQ上看到消息确实发出来了，而当文本较长或是图片、音频等除文本以外的消息时，报错相同，而QQ中看不到消息。

### 如何复现

nonebot的安装遵照[文档](https://nonebot.dev/docs/quick-start)进行。
LLOneBot的安装也完全遵照其[文档](https://llonebot.github.io/zh-CN/guide/nonebot2)进行。
反向ws使用nonebot[文档](https://nonebot.dev/docs/tutorial/application)中的配置
```
HOST=0.0.0.0  # 配置 NoneBot 监听的 IP / 主机名
PORT=8080  # 配置 NoneBot 监听的端口
```
正向ws使用onebot适配器[文档](https://onebot.adapters.nonebot.dev/docs/guide/installation)中的配置
`ONEBOT_WS_URLS=["ws://127.0.0.1:6700"]`
对应的LLOneBot配置如下图

![image](https://github.com/nonebot/nonebot2/assets/47747022/c8560ea0-e800-4add-82e0-0d52c8f128b3)

配置完成后启动nonebot，看到日志输出协议端连接成功，然后在QQ中发送指令，之后就出现报错。
在之后不断的尝试中发现虽然报错，但QQ中能收到短文本消息，收不到长文本或图片、音频等特殊类型的消息。

### 期望的结果?

正常发送各类受支持的消息（包括但不限于文本、图片、语音等）

### LLOneBot 运行日志

```shell
2024/6/9 09:43:52 亚托莉(<机器人QQ号>): ws 消息上报 ws://127.0.0.1:8081/onebot/v11/ws/ {"self_id":<机器人QQ号>,"user_id":<用户QQ号>,"time":1717897432,"message_id":-2147482813,"real_id":-2147482813,"message_seq":-2147482813,"message_type":"group","sender":{"user_id":<用户QQ号>,"nickname":"꧁不̶死̶鸟̶A̶n̶k̶a̶༼༽","card":"","role":"admin"},"raw_message":"rd 3d6","font":14,"sub_type":"normal","message":[{"data":{"text":"rd 3d6"},"type":"text"}],"message_format":"array","post_type":"message","group_id":<QQ群号>} 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): ws 消息上报  {"self_id":<机器人QQ号>,"user_id":<用户QQ号>,"time":1717897432,"message_id":-2147482813,"real_id":-2147482813,"message_seq":-2147482813,"message_type":"group","sender":{"user_id":<用户QQ号>,"nickname":"꧁不̶死̶鸟̶A̶n̶k̶a̶༼༽","card":"","role":"admin"},"raw_message":"rd 3d6","font":14,"sub_type":"normal","message":[{"data":{"text":"rd 3d6"},"type":"text"}],"message_format":"array","post_type":"message","group_id":<QQ群号>} 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): 收到反向Websocket消息 {"action":"send_msg","params":{"user_id":<用户QQ号>,"group_id":<QQ群号>,"message_type":"group","message":[{"type":"text","data":{"text":"你掷出了3个6面骰子, 点数为【8】"}}]},"echo":"7"} 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): 发送消息总大小 0 bytes 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): 设置消息超时时间 5000 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): ws 消息上报 ws://127.0.0.1:8081/onebot/v11/ws/ {"time":1717897432,"self_id":<机器人QQ号>,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":1000} 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): ws 消息上报  {"time":1717897432,"self_id":<机器人QQ号>,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":1000} 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): ws 消息上报 ws://127.0.0.1:8081/onebot/v11/ws/ {"time":1717897432,"self_id":<机器人QQ号>,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":1000} 

2024/6/9 09:43:52 亚托莉(<机器人QQ号>): ws 消息上报  {"time":1717897432,"self_id":<机器人QQ号>,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":1000} 

2024/6/9 09:43:53 亚托莉(<机器人QQ号>): message update 7452530323665934133 {"msgId":"7452530323665934133","msgRandom":"52703154","msgSeq":"9335","cntSeq":"0","chatType":2,"msgType":2,"subMsgType":1,"sendType":1,"senderUid":"u_LeZEYWgzMlwucnn88gnoJA","peerUid":"<QQ群号>","channelId":"","guildId":"undefined","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1717897432","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"亚托莉","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7378313290322406462","extBufForUI":"0x","textElement":{"content":"你掷出了3个6面骰子, 点数为【8】","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"小Anka、小小不死鸟～","freqLimitInfo":null,"editable":true,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"9731","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"<机器人QQ号>","peerUin":"<QQ群号>","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null} 

2024/6/9 09:43:53 亚托莉(<机器人QQ号>): ws 消息上报 ws://127.0.0.1:8081/onebot/v11/ws/ {"time":1717897433,"self_id":<机器人QQ号>,"post_type":"meta_event","meta_event_type":"heartbeat","status":{"online":true,"good":true},"interval":1000} 

<此处省略ws正常消息上报日志>

2024/6/9 09:43:58 亚托莉(<机器人QQ号>): 发生错误 发送超时 

<后面继续ws消息上报>
```

### OneBot 客户端运行日志

```shell
06-09 09:43:58 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_roll, lineno=28) running complete
06-09 09:43:58 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_roll, lineno=28) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot_plugin_roll\__init__.py", line 106, in _
    await matcher.finish(f"你掷出了{dice_num}个{dice_side}面骰子, 点数为【{dice_result}】")
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 582, in finish
    await cls.send(message, **kwargs)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "D:\Portable-Program-Files\nonebot\LLOneBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo='7')
```

**Comment by linyuchen** [comment]
手动发送一下长文本或者图片看看是不是账号被风控了

**Comment by A-n-k-a** [comment]
已尝试手动发送长文本，出现了电脑端显示发送成功，但其他群成员看不到的情况。
已尝试手动发送图片，能正常发送，且其他群成员能收到。

通过更多的测试发现似乎是群内另一个机器人在复读消息导致报错。
为便于描述，下称我的机器人为A，群内另一个机器人为B。
具体现象描述：
A发送了一条消息，nonebot日志显示发送成功（且群内确实能看到这条消息），B立即复读消息，3-5秒后便出现
`2024/6/9 09:43:58 亚托莉(<机器人QQ号>): 发生错误 发送超时`这种报错，之后A再发消息就发不了了。
之后我新建了一个群聊，只有我和机器人在里面，再次测试发送消息，发现能够正常发送，但会偶发性地出现
```
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<get() done, defined at /media/datapart/ATRI/ATRI/utils/request.py:16> exception=ConnectError('All connection attempts failed')>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 165, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2301, in connect_tcp
    await get_running_loop().create_connection(
  File "uvloop/loop.pyx", line 2039, in create_connection
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/anyio/_core/_sockets.py", line 227, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 109, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/datapart/ATRI/ATRI/utils/request.py", line 19, in get
    return await client.get(url, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/pypoetry/virtualenvs/atri-EZPc0nDf-py3.10/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
```
这种报错，目前暂未发现复现方法，且暂未发现该报错对机器人有何影响，输出错误信息之后仍能收发消息。

**Comment by jhqwqmc** [comment]
多半是被风控了，先养养号吧

**Comment by A-n-k-a** [comment]
好的，谢谢
