### ISSUE TITLE
[BUG] 无法下载mp4视频文件

### ISSUE THREAD

**Issue by jhqwqmc** [LLOneBot/LLOneBot#254]
### 系统版本

Windows Server 2022 Standard 21H2

### QQNT 版本

9.9.11-24402

### LLOneBot 版本

3.26.6

### OneBot 客户端

nonebot-adapter-onebot 2.4.3

### 发生了什么?

`get_file`接口无法获取文件类型为mp4的文件

### 如何复现

1. qq用户上传mp4类型文件（非mp4改后缀无效）
2. 使用`nonebot`的`nonebot-adapter-onebot`适配器调用`get_file`接口
3. 机器人处理完毕返回的时候会显示断开，但nonebot显示并没有断开日志，机器人尝试重新连接但是在nonebot看来是重复连接，所以拒绝（403）多次重试后nonebot显示断开并且机器人重新连接，然后等待调用接口的超时报错

### 期望的结果?

可以正常的返回内容

### LLOneBot 运行日志

```shell
2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): message update 【MSGID】 {"msgId":"【MSGID】","msgRandom":"【可能被利用追踪的消息1】","msgSeq":"【可能被利用追踪的消息2】","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":4,"sendType":0,"senderUid":"【UID】","peerUid":"【群号】","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"【消息时间】","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"【发送者昵称】","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7379218055250574336","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":1,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"【发送者qq号】","peerUin":"【群号】","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): ws 消息上报 ws://【服务器ip】:8080/onebot/v11/ws {"self_id":【机器人qq号】,"user_id":【发送者qq号】,"time":【消息时间】,"message_id":【消息id】,"real_id":【消息id】,"message_seq":【消息id】,"message_type":"group","sender":{"user_id":【发送者qq号】,"nickname":"【发送者昵称】","card":"","role":"member"},"raw_message":"[CQ:file,file=【文件名称】,path=,file_id=/【文件id】,file_size=【文件大小】]","font":14,"sub_type":"normal","message":[{"data":{"file":"【文件名称】","path":"","file_id":"/【文件id】","file_size":"【文件大小】"},"type":"file"}],"message_format":"array","post_type":"message","group_id":【群号】} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): ws 消息上报 ws://【服务器ip】:8080/onebot/v11/ws {"time":1718108123,"self_id":【机器人qq号】,"post_type":"notice","group_id":【群号】,"user_id":【发送者qq号】,"notice_type":"group_upload","file":{"id":"/【文件id】","name":"【文件名称】","size":【文件大小】,"busid":102}} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): message update 【MSGID】 {"msgId":"【MSGID】","msgRandom":"【可能被利用追踪的消息1】","msgSeq":"【可能被利用追踪的消息2】","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":4,"sendType":0,"senderUid":"【UID】","peerUid":"【群号】","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"【消息时间】","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"【发送者昵称】","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7379218055250574336","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":1,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"【发送者qq号】","peerUin":"【群号】","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): 收到反向Websocket消息 {"action":"get_file","params":{"file_id":"/【文件id】"},"echo":"2"} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): 需要调用 NTQQ 下载文件api 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): 找到了文件 msg {"msgId":"【MSGID】","msgRandom":"【可能被利用追踪的消息1】","msgSeq":"【可能被利用追踪的消息2】","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":4,"sendType":0,"senderUid":"【UID】","peerUid":"【群号】","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"【消息时间】","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"【发送者昵称】","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7379218055250574336","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":1,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"【发送者qq号】","peerUin":"【群号】","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"msgShortId":【消息id】} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): 找到了文件 element {"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":1,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0} 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): nodeIKernelMsgService/downloadRichMedia callback undefined 

2024/6/11 20:15:23 【机器人昵称】(【机器人qq号】): message update 【MSGID】 {"msgId":"【MSGID】","msgRandom":"【可能被利用追踪的消息1】","msgSeq":"【可能被利用追踪的消息2】","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":4,"sendType":0,"senderUid":"【UID】","peerUid":"【群号】","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"【消息时间】","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"【发送者昵称】","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7379218055250574336","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":3,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"【发送者qq号】","peerUin":"【群号】","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null} 

2024/6/11 20:15:24 【机器人昵称】(【机器人qq号】): media 下载完成判断 【MSGID】 【MSGID】 

2024/6/11 20:15:24 【机器人昵称】(【机器人qq号】): message update 【MSGID】 {"msgId":"【MSGID】","msgRandom":"【可能被利用追踪的消息1】","msgSeq":"【可能被利用追踪的消息2】","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":4,"sendType":0,"senderUid":"【UID】","peerUid":"【群号】","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"【消息时间】","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"【发送者昵称】","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7379218055250574336","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"C:\\Users\\Administrator\\Downloads\\QQ\\Fishing (3).mp4","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":4,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"【发送者qq号】","peerUin":"【群号】","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null} 

2024/6/11 20:15:25 【机器人昵称】(【机器人qq号】): 下载完成后的msg {"msgId":"【MSGID】","msgRandom":"【可能被利用追踪的消息1】","msgSeq":"【可能被利用追踪的消息2】","cntSeq":"0","chatType":2,"msgType":3,"subMsgType":4,"sendType":0,"senderUid":"【UID】","peerUid":"【群号】","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"【消息时间】","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"【发送者昵称】","guildName":"","channelName":"","elements":[{"elementType":3,"elementId":"7379218055250574336","extBufForUI":"0x","textElement":null,"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":{"fileMd5":"【文件MD5】","fileName":"【文件名称】","filePath":"C:\\Users\\Administrator\\Downloads\\QQ\\Fishing (3).mp4","fileSize":"【文件大小】","picHeight":518,"picWidth":868,"picThumbPath":{},"expireTime":"0","file10MMd5":"","fileSha":"","fileSha3":"","videoDuration":0,"transferStatus":4,"progress":0,"invalidState":0,"fileUuid":"/【文件id】","fileSubId":"","thumbFileSize":0,"fileBizId":102,"thumbMd5":null,"folderId":null,"fileGroupIndex":0,"fileTransType":null,"subElementType":2,"storeID":0},"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":false,"generalFlags":"0x","clientSeq":"0","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"【发送者qq号】","peerUin":"【群号】","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"msgShortId":【消息id】} 

2024/6/11 20:15:26 【机器人昵称】(【机器人qq号】): ws 消息上报 ws://【服务器ip】:8080/onebot/v11/ws {"status":"ok","retcode":0,"data":{"file":"C:\\Users\\Administrator\\Downloads\\QQ\\Fishing (3).mp4","file_size":"【文件大小】","file_name":"【文件名称】","base64":"【文件BASE64】"},"message":"","wording":"","echo":"2"} 

2024/6/11 20:15:26 【机器人昵称】(【机器人qq号】): The websocket connection: ws://【服务器ip】:8080/onebot/v11/ws closed, trying reconnecting... 

2024/6/11 20:15:26 【机器人昵称】(【机器人qq号】): 反向ws断开 ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:29 【机器人昵称】(【机器人qq号】): Trying to connect to the websocket server: ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:29 【机器人昵称】(【机器人qq号】): {} 

2024/6/11 20:15:29 【机器人昵称】(【机器人qq号】): The websocket connection: ws://【服务器ip】:8080/onebot/v11/ws closed, trying reconnecting... 

2024/6/11 20:15:29 【机器人昵称】(【机器人qq号】): 反向ws断开 ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:32 【机器人昵称】(【机器人qq号】): Trying to connect to the websocket server: ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:32 【机器人昵称】(【机器人qq号】): {} 

2024/6/11 20:15:32 【机器人昵称】(【机器人qq号】): The websocket connection: ws://【服务器ip】:8080/onebot/v11/ws closed, trying reconnecting... 

2024/6/11 20:15:32 【机器人昵称】(【机器人qq号】): 反向ws断开 ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:35 【机器人昵称】(【机器人qq号】): Trying to connect to the websocket server: ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:35 【机器人昵称】(【机器人qq号】): The websocket connection: ws://【服务器ip】:8080/onebot/v11/ws closed, trying reconnecting... 

2024/6/11 20:15:35 【机器人昵称】(【机器人qq号】): {} 

2024/6/11 20:15:35 【机器人昵称】(【机器人qq号】): 反向ws断开 ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:38 【机器人昵称】(【机器人qq号】): Trying to connect to the websocket server: ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:38 【机器人昵称】(【机器人qq号】): Connected to the websocket server: ws://【服务器ip】:8080/onebot/v11/ws 

2024/6/11 20:15:38 【机器人昵称】(【机器人qq号】): ws 消息上报 ws://【服务器ip】:8080/onebot/v11/ws {"time":1718108138,"self_id":【机器人qq号】,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}
```

### OneBot 客户端运行日志

```shell
06-11 20:14:43 [SUCCESS] nonebot | OneBot V11 【机器人qq号】 | [message.group.normal]: Message 【消息id】 from 【发送者qq号】@[群:【群号】] '[file:file=【文件名称】,path=,file_id=/【文件id】,file_size=【文件大小】]'
06-11 20:14:43 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.content_review, lineno=357)
06-11 20:14:43 [SUCCESS] nonebot | OneBot V11 【机器人qq号】 | [notice.group_upload]: {'time': 【消息时间】, 'self_id': 【机器人qq号】, 'post_type': 'notice', 'notice_type': 'group_upload', 'user_id': 【发送者qq号】, 'group_id': 【群号】, 'file': {'id': '/【文件id】', 'name': '【文件名称】', 'size': 【文件大小】, 'busid': 102}}
06-11 20:14:43 [INFO] content_review | ==========================
06-11 20:14:43 [INFO] content_review | [{'type': 'file', 'data': {'file': '【文件名称】', 'path': '', 'file_id': '/【文件id】', 'file_size': '【文件大小】'}}]
06-11 20:14:43 [INFO] content_review | ==========================
06-11 20:14:49 [WARNING] nonebot | OneBot V11 | There's already a bot 【机器人qq号】, ignored
06-11 20:14:49 [INFO] uvicorn | ('【服务器ip】', 27666) - "WebSocket /onebot/v11/ws" 403
06-11 20:14:49 [INFO] websockets | connection rejected (403 Forbidden)
06-11 20:14:49 [INFO] websockets | connection closed
06-11 20:14:52 [WARNING] nonebot | OneBot V11 | There's already a bot 【机器人qq号】, ignored
06-11 20:14:52 [INFO] uvicorn | ('【服务器ip】', 27685) - "WebSocket /onebot/v11/ws" 403
06-11 20:14:52 [INFO] websockets | connection rejected (403 Forbidden)
06-11 20:14:52 [INFO] websockets | connection closed
06-11 20:14:55 [WARNING] nonebot | OneBot V11 | There's already a bot 【机器人qq号】, ignored
06-11 20:14:55 [INFO] uvicorn | ('【服务器ip】', 27696) - "WebSocket /onebot/v11/ws" 403
06-11 20:14:55 [INFO] websockets | connection rejected (403 Forbidden)
06-11 20:14:55 [INFO] websockets | connection closed
06-11 20:14:56 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 【机器人qq号】 closed by peer
06-11 20:14:56 [INFO] websockets | connection closed
06-11 20:14:58 [INFO] uvicorn | ('【服务器ip】', 27731) - "WebSocket /onebot/v11/ws" [accepted]
06-11 20:14:58 [INFO] nonebot | OneBot V11 | Bot 【机器人qq号】 connected
06-11 20:14:58 [INFO] websockets | connection open
06-11 20:15:13 [INFO] nonebot | Matcher(type='message', module=plugins.content_review, lineno=357) running complete
06-11 20:15:13 [ERROR] nonebot | Running Matcher(type='message', module=plugins.content_review, lineno=357) failed.
Traceback (most recent call last):
  File "d:\Desktop\python\qqbot\momiqqbot\main.py", line 18, in <module>
    Main()
  File "d:\Desktop\python\qqbot\momiqqbot\main.py", line 14, in __init__
    nonebot.run()
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Program Files\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Program Files\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "d:\Desktop\python\qqbot\momiqqbot\plugins\content_review\__init__.py", line 368, in msg_handle
    parse_video_msg = await cos_audit.video_handle(bot, msg)
  File "d:\Desktop\python\qqbot\momiqqbot\plugins\content_review\__init__.py", line 349, in video_handle
    data: dict = await bot.call_api("get_file", file_id=video_id)
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\Desktop\python\qqbot\momiqqbot\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 149, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api get_file timeout')
```

**Comment by jhqwqmc** [comment]
> 用上报的video url直接下载，不需要调用get_file

上传的mp4文件没有url字段

**Comment by jhqwqmc** [comment]
> 06-11 20:14:43 [INFO] content_review | ==========================
06-11 20:14:43 [INFO] content_review | [{'type': 'file', 'data': {'file': '【文件名称】', 'path': '', 'file_id': '/【文件id】', 'file_size': '【文件大小】'}}]
06-11 20:14:43 [INFO] content_review | ==========================

上面的`OneBot 客户端运行日志`有打印出上报的没有url字段

**Comment by jhqwqmc** [comment]
![image](https://github.com/LLOneBot/LLOneBot/assets/113768629/2b80e9eb-3b7d-4486-9db8-2f894df8a0c2)

**Comment by idranme** [comment]
尝试使用 v3.29.3
