### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CaiJingLong** [LLOneBot/LLOneBot#278]
### 系统版本

macOS 14.4.1 

### QQNT 版本

6.9.31-22578

### LLOneBot 版本

LLOneBot v3.26.7

### OneBot 客户端

koishi-adapter-onebot 6.5.8

### 发生了什么?

music 插件应该发送音乐信息时发送失败

### 如何复现

使用 koishi 的一个插件 music-downloadvoice-api ，让机器人发送音乐连接时触发

1. 使用正常QQ号发送给机器人消息 `music 搁浅`
2. 回复1，以让机器人回复音乐
3. 发送失败，koishi和LLOneBot均报错

### 期望的结果?

机器人应该正常发送音乐

### LLOneBot 运行日志

```shell
7/8/2024, 4:11:54 PM 糖果小蜜(776575158): 获取文件类型 mp3 /Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/LLOneBot/temp/7b583575-8932-4d34-96be-3d9faa1a2329M800004UlK9x0jeuow.mp3 

7/8/2024, 4:11:54 PM 糖果小蜜(776575158): 语音文件/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/data/LLOneBot/temp/7b583575-8932-4d34-96be-3d9faa1a2329M800004UlK9x0jeuow.mp3.mp3需要转换成silk 

7/8/2024, 4:11:54 PM 糖果小蜜(776575158): convert silk failed Error: spawn EPERM
    at ChildProcess.spawn (node:internal/child_process:414:11)
    at Object.spawn (node:child_process:784:9)
    at /Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:26355:41
    at new Promise (<anonymous>)
    at convert (/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:26353:16)
    at encodeSilk (/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:26376:23)
    at async SendMsgElementConstructor.ptt (/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:31713:53)
    at async createSendElements (/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:32229:35)
    at async SendPrivateMsg._handle (/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:32448:52)
    at async SendPrivateMsg.websocketHandle (/Users/cai/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:31884:23)
```

### OneBot 客户端运行日志

```shell
Error: Error with request send_private_msg, args: {"user_id":262990989,"message":[{"type":"record","data":{"duration":240,"file":"http://ws.stream.qqmusic.qq.com/http://isure6.stream.qqmusic.qq.com/M800004UlK9x0jeuow.mp3?fromtag=810033622&guid=br_xzg&src=M800001Bbywq2gicae.mp3&trace=1ed664962a487a5b&uin=553&vkey=359D26EDDDCA44BD86A83F38A2355977866AA7455C6EC0E9D829A0235A6BEA6C2949AC4D1D4783959A72586036268E825DE0D90018FEB353","cache":0}}]}, retcode: 1200
                            at _Internal._get (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/koishi-plugin-adapter-onebot/lib/index.js:780:227)
                            at async OneBotMessageEncoder.send (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/@satorijs/core/lib/index.cjs:616:5)
                            at async Proxy.sendMessage (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/@satorijs/core/lib/index.cjs:346:22)
                            at async Command.<anonymous> (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/koishi-plugin-music-downloadvoice-api/lib/index.js:245:9)
                            at async Array.<anonymous> (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/@koishijs/core/lib/index.cjs:1114:14)
                            at async Command.execute (/Users/cai/code/qqbots/koishi-app-qqbot/node_modules/@koishijs/core/lib/index.cjs:1128:22)
                            at async /Users/cai/code/qqbots/koishi-app-qqbot/node_modules/@koishijs/core/lib/index.cjs:2162:22
```

**Comment by CaiJingLong** [comment]
补充一下其他信息：
日志中的文件信息，和我的ffmpeg信息如下

<img width="1362" alt="image" src="https://github.com/LLOneBot/LLOneBot/assets/14145407/4a314c87-1028-4585-94c8-084178d2abe9">
<img width="596" alt="image" src="https://github.com/LLOneBot/LLOneBot/assets/14145407/9bebb168-702e-461e-89e2-225e89f634ca">

**Comment by idranme** [comment]
尝试重装 FFmpeg

**Comment by CaiJingLong** [comment]
指定与否都无法输出，然后我切到 Napcat 就没再试这个了
