### ISSUE TITLE
[BUG] 无法同意进群申请

### ISSUE THREAD

**Issue by yxjsxl** [LLOneBot/LLOneBot#286]
### 系统版本

Windows Server 2022

### QQNT 版本

9.9.7

### LLOneBot 版本

3.18.0

### OneBot 客户端

最新的

### 发生了什么?

发送正向ws请求同意进群邀请时出现报错，有管理员:
Received message: {'status': 'failed', 'retcode': 1200, 'data': None, 'message': "TypeError: Cannot read properties of undefined (reading 'toString')\n    at SetGroupAddRequest._handle (D:\\server\\qqbot\\LiteLoaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:34292:37)\n    at SetGroupAddRequest.websocketHandle (D:\\server\\qqbot\\LiteLoaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:31884:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OB11WebsocketServer.handleAction (D:\\server\\qqbot\\LiteLoaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:80925:26)", 'wording': "TypeError: Cannot read properties of undefined (reading 'toString')\n    at SetGroupAddRequest._handle (D:\\server\\qqbot\\LiteLoaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:34292:37)\n    at SetGroupAddRequest.websocketHandle (D:\\server\\qqbot\\LiteLoaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:31884:34)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async OB11WebsocketServer.handleAction (D:\\server\\qqbot\\LiteLoaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:80925:26)"}

### 如何复现

1.发送ws同意进群请求
2.错误复现

### 期望的结果?

同意进群申请

**Comment by yxjsxl** [comment]
应在SetGroupAddRequest方法中判断approve是否为空,改入如下代码
`
if (payload.approve === null){
    const approve = true;
} else if (payload.approve.toString() === "true"){
    const approve = true;
}else{
    const approve = false;
}
`
