### ISSUE TITLE
[BUG] 无法发送私聊消息

### ISSUE THREAD

**Issue by kzqj** [LLOneBot/LLOneBot#321]
### 系统版本

Windows 10

### QQNT 版本

9.9.15-26740

### LLOneBot 版本

3.28.0

### OneBot 客户端

nonebot2

### 发生了什么?

收到反向Websocket消息后，llob无法向私聊好友发送消息，日志显示刷新好友列表失败和不能发送临时消息，群聊正常
是qq版本过新导致？

### 如何复现

建立反向ws后向好友发送消息

### 期望的结果?

正常发送消息

### LLOneBot 运行日志

```shell
2024/8/9 11:20:49 (2506068455): 收到反向Websocket消息 {"action":"send_msg","params":{"user_id":93190,"message_type":"private","message":[{"type":"text","data":{"text":"/manga \nUnknown\n\n可用的子命令},"echo":"5"} 

2024/8/9 11:20:49 (2506068455): nodeIKernelBuddyService/getBuddyList callback {"result":0,"errMsg":"success"} 

2024/8/9 11:20:49 (2506068455): nodeIKernelBuddyService/getBuddyList callback {"result":0,"errMsg":"success"} 

2024/8/9 11:20:49 (2506068455): hook error {} {"buddyCategory":[{"categoryId":9999,"categorySortId":0,"categroyName":"特别关心","categroyMbCount":0,"onlineCount":0,"buddyUids":[]},{"categoryId":0,"categorySortId":0,"categroyName":"我的好友","categroyMbCount":6,"onlineCount":5,"buddyUids":["u_G_JWSMgb78auqeJXPIvQXg","u_BXbRy5Tz4sTXv-JxOyZ11g","u_u_obuFM77-Oi2SjXhwD16Q","u_GUydI9XPa7ruWz0TtfMihg","u_0f1mfYWivKjDqgoSjlA_qQ","u_g4H0I4j69OkyVYSAaiu85Q"]}],"userSimpleInfos":{"u_BXbRy5Tz4sTXv-JxOyZ11g":{"uid":"u_BXbRy5Tz4sTXv-JxOyZ11g","uin":"78351","coreInfo":{"uid":"u_BXbRy5Tz4sTXv-JxOyZ11g","uin":"3178351","nick":"","remark":""},"baseInfo":{"qid":"XJTUSUjxq","longNick":台","birthday_year":2018,"birthday_month":7,"birthday_day":11,"age":6,"sex":2,"eMail":"","phoneNum":"-","categoryId":0,"richTime":1657642951, 此处省略较长信息

2024/8/9 11:20:49 (2506068455): 刷新好友列表失败 TypeError: i.data is not iterable
    at ri.getFriends (C:\Users\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:584)
    at async Pa (C:\Users\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:75790)
    at async Na.check (C:\Users\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:58832)
    at async Na.websocketHandle (C:\Users\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:51171)
    at async r_.onmessage (C:\Users\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:346:6265)
    at async WebSocket.<anonymous> (C:\Users\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:346:7102) 

2024/8/9 11:20:49 (2506068455): ws 消息上报 ws://127.0.0.1:23770/onebot/v11/ws/ {"status":"failed","retcode":1400,"data":null,"message":"不能发送临时消息","wording":"不能发送临时消息","echo":null}
```

### OneBot 客户端运行日志

```shell
[DEBUG] nonebot | OneBot V11 | Calling API send_msg

    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_msg timeout')
```

**Comment by idranme** [comment]
[v3.28.1](https://github.com/LLOneBot/LLOneBot/releases/tag/v3.28.1) 已修复
