### ISSUE TITLE
[BUG] 群戳戳当戳bot时抓取不到"target_id，返回为null

### ISSUE THREAD

**Issue by luqing233** [LLOneBot/LLOneBot#326]
### 系统版本

Windows 11 家庭中文版 23H2 

### QQNT 版本

9.9.15-26909

### LLOneBot 版本

3.28.2

### OneBot 客户端

overflow-2.16.0-0c5f30a-SNAPSHOT

### 发生了什么?

无法获取"target_id"，监听端口发现消息段为（）
{"time":1723277522,"self_id":19702*****,"post_type":"notice","notice_type":"notify","sub_type":"poke","target_id":null,"raw_message":[{"col":"1","nm":"","type":"qq","uid":"u_1GiWbu9wIQ_JvDNWYg6dmw"},{"jp":"https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&actionId=8","src":"http://tianquan.gtimg.cn/nudgeaction/item/8/expression.jpg","type":"img"},{"txt":"揉了揉","type":"nor"},{"col":"1","nm":"","tp":"0","type":"qq","uid":"u_FetXI_oPjMC6hOyZXBQXxw"},{"txt":"的头并拔了一根呆毛","type":"nor"}],"user_id":3253******,"group_id":68859****

### 如何复现

当有戳戳事件且对象为bot时就会发生

### 期望的结果?

target_id 的值应为bot的qq

### LLOneBot 运行日志

```shell
2024/8/10 16:40:20 伊蕾娜(19702*****): ws 消息上报  {"time":1723279220,"self_id":19702*****,"post_type":"notice","notice_type":"notify","sub_type":"poke","target_id":null,"raw_message":[{"col":"1","nm":"","type":"qq","uid":"u_1GiWbu9wIQ_JvDNWYg6dmw"},{"jp":"https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&actionId=8","src":"http://tianquan.gtimg.cn/nudgeaction/item/8/expression.jpg","type":"img"},{"txt":"揉了揉","type":"nor"},{"col":"1","nm":"","tp":"0","type":"qq","uid":"u_FetXI_oPjMC6hOyZXBQXxw"},{"txt":"的头并拔了一根呆毛","type":"nor"}],"user_id":32539*****,"group_id":6885*****} 

2024/8/10 16:40:20 伊蕾娜(19702*****): 收到正向Websocket消息 {"action":"get_group_member_info","params":{"group_id":6885*****,"user_id":0,"no_cache":false},"echo":21} 

2024/8/10 16:40:20 伊蕾娜(19702*****): 发生错误 群成员0不存在 

2024/8/10 16:40:20 伊蕾娜(19702*****): ws 消息上报  {"status":"failed","retcode":1200,"data":null,"message":"群成员0不存在","wording":"群成员0不存在","echo":21}
```

### OneBot 客户端运行日志

```shell
2024-08-10 16:08:35 W/Onebot: 请求失败: [get_group_member_info] 请求失败: app=LLOneBot v3.28.2, message=群成员0不存在, retJson={"status":"failed","retcode":1200,"data":null,"message":"群成员0不存在","wording":"群成员0不存在","echo":6}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-08-10 16:08:35 W/stderr: Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: 群 688****** 戳一戳事件 无法获取目标
2024-08-10 16:08:35 W/stderr:   at top.mrxiaom.overflow.internal.listener.NotifyNoticeListener.onMessage(bot.kt:46)
2024-08-10 16:08:35 W/stderr:   at top.mrxiaom.overflow.internal.listener.NotifyNoticeListener$onMessage$1.invokeSuspend(bot.kt)
2024-08-10 16:08:35 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2024-08-10 16:08:35 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-08-10 16:08:35 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2024-08-10 16:08:35 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(overflow), StandaloneCoroutine{Cancelling}@2c25526f, Dispatchers.Default]
```

**Comment by idranme** [comment]
v3.28.3 已修复
