### ISSUE TITLE
[BUG] 在收到进群申请时无法通过get_stranger_info获取对方信息

### ISSUE THREAD

**Issue by skongkonga** [LLOneBot/LLOneBot#327]
### 系统版本

Windows Server 2022 Datacenter 21H2

### QQNT 版本

9.9.15-26909

### LLOneBot 版本

3.28.2

### OneBot 客户端

Nonebot2

### 发生了什么?

在收到进群申请时，欲使用get_stranger_info获取对方信息如qq等级等，但提示查无此人

类似于 #270 ，但我看get_stranger_info理论上是能够获取到加群者的信息的：https://github.com/LLOneBot/LLOneBot/issues/213#issuecomment-2101090664

### 如何复现

1.给qq群入群方式设置为：需要回答问题并由管理员审核
2.编写对应逻辑。在收到进群申请的时候使用user_id（qq号）通过get_stranger_info获取对方信息。
3.使用另一qq加入bot所在群，便可触发报错

### 期望的结果?

能够正确获取加群者的信息

### LLOneBot 运行日志

```shell
Error: 查无此人
    at Z4._handle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:101299)
    at Z4.websocketHandle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:62598)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c_.onmessage (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:6266)
    at async WebSocket.<anonymous> (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:7103)', wording='Error: 查无此人
    at Z4._handle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:101299)
    at Z4.websocketHandle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:62598)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c_.onmessage (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:6266)
    at async WebSocket.<anonymous> (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:7103)
```

### OneBot 客户端运行日志

```shell
08-10 16:42:49 [ERROR] nonebot | Running Matcher(type='request', module=mybot.plugins.my_autoconsent) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\mybot\.\mybot\plugins\my_autoconsent\__init__.py", line 61, in _
    user_info = await bot.get_stranger_info(user_id=uid)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: 查无此人\n    at Z4._handle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:101299)\n    at Z4.websocketHandle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:62598)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async c_.onmessage (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:6266)\n    at async WebSocket.<anonymous> (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:7103)', wording='Error: 查无此人\n    at Z4._handle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:101299)\n    at Z4.websocketHandle (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:24:62598)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async c_.onmessage (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:6266)\n    at async WebSocket.<anonymous> (D:\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:346:7103)', echo='26')
```

**Comment by idranme** [comment]
v3.28.3 已修复
