### ISSUE TITLE
[BUG] 单向好友临时会话无法发送消息

### ISSUE THREAD

**Issue by miiiiiint** [LLOneBot/LLOneBot#332]
### 系统版本

Microsoft Windows 11 专业版

### QQNT 版本

9.9.12-25493

### LLOneBot 版本

3.28.6

### OneBot 客户端

nonebot

### 发生了什么?

猜测无法正常获取此类会话的用户uid

### 如何复现

bot账号设置正确回答问题添加好友。
添加好友后，其他账号与bot账号此时可以进行会话，但是对于bot账户来说是临时会话。
bot无法在这个会话发送消息。
bot尝试在这个会话发送消息时会出现报错。

### 期望的结果?

通过其他方式获取到用户uid

### LLOneBot 运行日志

```shell
2024/8/12 13:18:44 undefined(1240256904): {"msgId":"7402118110470118252","msgRandom":"1574425904","msgSeq":"10","cntSeq":"0","chatType":1,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_GMFOSKD78WGhYA6kQM4hWg","peerUid":"u_GMFOSKD78WGhYA6kQM4hWg","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1723439924","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7402118110470118251","extBufForUI":"0x","textElement":{"content":"你好","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":"0x","clientSeq":"7929","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"319373385","peerUin":"319373385","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"msgShortId":-2147483463} 

2024/8/12 13:18:44 undefined(1240256904): ws 消息上报 ws://127.0.0.1:8080/onebot/v11/ws {"self_id":1240256904,"user_id":319373385,"time":1723439924,"message_id":-2147483463,"real_id":-2147483463,"message_seq":-2147483463,"message_type":"private","sender":{"user_id":319373385,"nickname":"LEAVE0_O","card":""},"raw_message":"你好","font":14,"sub_type":"friend","message":[{"data":{"text":"你好"},"type":"text"}],"message_format":"array","post_type":"message","raw":{"msgId":"7402118110470118252","msgRandom":"1574425904","msgSeq":"10","cntSeq":"0","chatType":1,"msgType":2,"subMsgType":1,"sendType":0,"senderUid":"u_GMFOSKD78WGhYA6kQM4hWg","peerUid":"u_GMFOSKD78WGhYA6kQM4hWg","channelId":"","guildId":"","guildCode":"0","fromUid":"0","fromAppid":"0","msgTime":"1723439924","msgMeta":"0x","sendStatus":2,"sendRemarkName":"","sendMemberName":"","sendNickName":"","guildName":"","channelName":"","elements":[{"elementType":1,"elementId":"7402118110470118251","extBufForUI":"0x","textElement":{"content":"你好","atType":0,"atUid":"0","atTinyId":"0","atNtUid":"","subElementType":0,"atChannelId":"0","linkInfo":null,"atRoleId":"0","atRoleColor":0,"atRoleName":"","needNotify":0},"faceElement":null,"marketFaceElement":null,"replyElement":null,"picElement":null,"pttElement":null,"videoElement":null,"grayTipElement":null,"arkElement":null,"fileElement":null,"liveGiftElement":null,"markdownElement":null,"structLongMsgElement":null,"multiForwardMsgElement":null,"giphyElement":null,"walletElement":null,"inlineKeyboardElement":null,"textGiftElement":null,"calendarElement":null,"yoloGameResultElement":null,"avRecordElement":null,"structMsgElement":null,"faceBubbleElement":null,"shareLocationElement":null,"tofuRecordElement":null,"taskTopMsgElement":null,"recommendedMsgElement":null,"actionBarElement":null}],"records":[],"emojiLikesList":[],"commentCnt":"0","directMsgFlag":0,"directMsgMembers":[],"peerName":"","freqLimitInfo":null,"editable":false,"avatarMeta":"","avatarPendant":"","feedId":"","roleId":"0","timeStamp":"0","clientIdentityInfo":null,"isImportMsg":false,"atType":0,"roleType":0,"fromChannelRoleInfo":{"roleId":"0","name":"","color":0},"fromGuildRoleInfo":{"roleId":"0","name":"","color":0},"levelRoleInfo":{"roleId":"0","name":"","color":0},"recallTime":"0","isOnlineMsg":true,"generalFlags":"0x","clientSeq":"7929","fileGroupSize":null,"foldingInfo":null,"multiTransInfo":null,"senderUin":"319373385","peerUin":"319373385","msgAttrs":{},"anonymousExtInfo":null,"nameType":0,"avatarFlag":0,"extInfoForUI":null,"personalMedal":null,"categoryManage":0,"msgEventInfo":null,"msgShortId":-2147483463}} 

2024/8/12 13:18:44 undefined(1240256904): 收到反向Websocket消息 {"action":"send_msg","params":{"user_id":319373385,"message_type":"private","message":[{"type":"text","data":{"text":"这是一条消息，可以使用CQ码"}},{"type":"image","data":{"file":"https://pixiv.re/103981177.png"}}]},"echo":"17"} 

2024/8/12 13:18:45 undefined(1240256904): 获取文件类型 jpg C:\Users\li\LiteLoaderQQNT-main\data\LLOneBot\temp\ed4a26e5-8c35-488e-bb8b-158860ac472c103981177.png 

2024/8/12 13:18:45 undefined(1240256904): 图片信息 {"md5HexStr":"e55017b486eb074ebc5e51ba01040d25","fileSize":"724152","picWidth":1190,"picHeight":1617,"fileName":"ed4a26e5-8c35-488e-bb8b-158860ac472c103981177.png.jpg","sourcePath":"C:\\Users\\li\\Documents\\Tencent Files\\1240256904\\nt_qq\\nt_data\\Pic\\2024-08\\Ori\\e55017b486eb074ebc5e51ba01040d25.jpg","original":true,"picType":1000,"picSubType":0,"fileUuid":"","fileSubId":"","thumbFileSize":0,"summary":""} 

2024/8/12 13:18:45 undefined(1240256904): 发送消息总大小 724152 bytes 

2024/8/12 13:18:45 undefined(1240256904): 设置消息超时时间 12071.796875
```

### OneBot 客户端运行日志

```shell
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 1,\n    "errMsg": ""\n}\n\n    at Timeout.h [as _onTimeout] (C:\\Users\\li\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:22:7460)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', wording='Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:\n{\n    "result": 1,\n    "errMsg": ""\n}\n\n    at Timeout.h [as _onTimeout] (C:\\Users\\li\\LiteLoaderQQNT-main\\plugins\\LLOneBot\\main\\main.cjs:22:7460)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)', echo='17')
```

**Comment by idranme** [comment]
v3.29.3 是否存在该问题？

**Comment by miiiiiint** [comment]
> v3.29.3 是否存在该问题？

经测试，仍存在同样问题，该问题是否无法复现？

**Comment by idranme** [comment]
v3.31.8 已修复
