### ISSUE TITLE
[BUG] 无法发送语音消息

### ISSUE THREAD

**Issue by cxchency** [LLOneBot/LLOneBot#348]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.12-26466

### LLOneBot 版本

3.29.4

### OneBot 客户端

koishi的onebot适配器转satori-server，再用python手搓satori适配

### 发生了什么?

LLOneBot 3.29.4 3.29.3 无法发送语音消息

### 如何复现

发送任意语音消息

### 期望的结果?

成功发送语音

### LLOneBot 运行日志

```shell
2024/8/18 22:10:32 店员(): 收到正向Websocket消息 {"action":"send_group_msg","params":{"group_id":,"message":[{"type":"record","data":{"file":"F:\\录音.mp3","cache":0}}]},"echo":7278742} 

2024/8/18 22:10:32 店员(): 发生错误 语音转换失败, 请检查语音文件是否正常 

2024/8/18 22:10:32 店员(): convert silk failed Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Documents\LiteloaderQQNT\data\LLOneBot\temp\dc5acc1e-1fed-4f17-903e-f07df97fda42'
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async Ww (C:\Users\Administrator\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:20:14695)
    at async rt.ptt (C:\Users\Administrator\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:62386)
    at async Ru (C:\Users\Administrator\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:28:92834)
    at async u2._handle (C:\Users\Administrator\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:28:95343)
    at async u2.websocketHandle (C:\Users\Administrator\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:24:64541)
    at async XI.handleAction (C:\Users\Administrator\Documents\LiteloaderQQNT\plugins\LLOneBot\main\main.cjs:350:15652)
```

**Comment by idranme** [comment]
v3.31.3 是否依然存在该问题？

**Comment by cxchency** [comment]
> v3.31.3 是否依然存在该问题？

已修复
