### ISSUE TITLE
[BUG] 不明原因导致不再上报事件

### ISSUE THREAD

**Issue by EatHatsuneShallots** [LLOneBot/LLOneBot#454]
### 系统版本

Windows Server 2016 Datacenter 1607

### QQNT 版本

9.9.12-25493

### LLOneBot 版本

3.33.10

### OneBot 客户端

ZeroBot-Plugin

### 发生了什么?

在一次发送合并转发消息失败后，会导致不再上报事件，除了元事件。客户端能收到消息
疑似是 IPC Timeout 导致

### 如何复现

不明，好像是使用 ZeroBot-Plugin 的 pixiv 插件时出现的

### 期望的结果?

正常发送合并转发消息，即使发送失败，也不至不再上报消息

### LLOneBot 运行日志

```shell
2024/9/30 23:16:24 [info] xxx(xxx) | onebot 收到正向 Websocket 消息 { action: 'send_private_msg', params: { message: [ { type: 'image', data: { file: 'file:///C:/Users/Administrator/Documents/Work/ZeroBot-Plugin-master/data/pixiv/xxxx.jpg' } } ], user_id: xxxx }, echo: 115 }

2024/9/30 23:16:29 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/getRichMediaFilePathForGuild ["nodeIKernelMsgService/getRichMediaFilePathForGuild",{"path_info":{"md5HexStr":"xxxxx","fileName":"xxxx.jpg","elementType":2,"elementSubType":0,"thumbSize":0,"needCreate":true,"downloadType":1,"file_uuid":""}}] 

2024/9/30 23:16:29 [error] xxx(xxx) | onebot 发生错误 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/getRichMediaFilePathForGuild, nodeIKernelMsgService/getRichMediaFilePathForGuild,[object Object]

2024/9/30 23:16:30 [info] xxx(xxx) | onebot 收到正向 Websocket 消息 { action: 'get_group_member_info', params: { group_id: xxxx, no_cache: false, user_id: xxxxx }, echo: 116 }

2024/9/30 23:16:35 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"xxxxx","bizList":[0]},null] 

2024/9/30 23:16:35 [error] xxx(xxx) | onebot 发生错误 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo, nodeIKernelProfileService/getUserDetailInfoWithBizInfo,[object Object],

2024/9/30 23:16:35 [info] xxx(xxx) | onebot 收到正向 Websocket 消息 { action: 'get_stranger_info', params: { no_cache: false, user_id: xxxxxx }, echo: 117 }

2024/9/30 23:16:40 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoByUin ["nodeIKernelProfileService/getUserDetailInfoByUin",{"uin":"xxxx"},null] 

2024/9/30 23:16:40 [error] xxx(xxx) | onebot 发生错误 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoByUin, nodeIKernelProfileService/getUserDetailInfoByUin,[object Object],

2024/9/30 23:16:41 [info] xxx(xxx) | onebot 收到正向 Websocket 消息 { action: 'get_group_member_info', params: { group_id: xxxxx, no_cache: false, user_id: xxxxx }, echo: 118 }

2024/9/30 23:16:46 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo ["nodeIKernelProfileService/getUserDetailInfoWithBizInfo",{"uid":"u_MrVSzsJFBolJ2SgzRgOB3A","bizList":[0]},null] 

2024/9/30 23:16:46 [error] xxx(xxx) | onebot 发生错误 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo, nodeIKernelProfileService/getUserDetailInfoWithBizInfo,[object Object],

2024/9/30 23:16:46 [info] xxx(xxx) | onebot 收到正向 Websocket 消息 { action: 'get_stranger_info', params: { no_cache: false, user_id: xxxxx }, echo: 119 }

2024/9/30 23:16:51 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoByUin ["nodeIKernelProfileService/getUserDetailInfoByUin",{"uin":"xxxxx"},null] 

2024/9/30 23:16:51 [error] xxx(xxx) | onebot 发生错误 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoByUin, nodeIKernelProfileService/getUserDetailInfoByUin,[object Object],

2024/9/30 23:16:51 [info] xxx(xxx) | onebot 收到正向 Websocket 消息 { action: 'send_group_forward_msg', params: { group_id: xxxxx, messages: [ { type: 'node', data: { content: '标题: xxxxxxxxx\n' + '插画ID: xxxxxx\n' + '画师: xxxxx\n' + '画师ID: xxxxxxx\n' + '直链: https://pixivel.moe/detail?id=xxxxxx', name: '', uin: 'xxxxx' } }, { type: 'node', data: { content: '[CQ:image,file=file:///C:/Users/Administrator/Documents/Work/ZeroBot-Plugin-master/data/pixiv/xxxxx.jpg]', name: '', uin: 'xxxxx' } } ] }, echo: 120 }

2024/9/30 23:16:51 [info] xxx(xxx) | onebot 开始生成转发节点 [ { elementType: 1, elementId: '', textElement: { content: '标题: xxxxxxxxx\n' + '插画ID: xxxxxx\n' + '画师: xxxxx\n' + '画师ID: xxxxxxx\n' + '直链: https://pixivel.moe/detail?id=xxxxxx', atType: 0, atUid: '', atTinyId: '', atNtUid: '' } } ]

2024/9/30 23:16:51 [info] xxx(xxx) | onebot 分割后的转发节点 [ [ { elementType: 1, elementId: '', textElement: { content: '标题: xxxxxxxxx\n' + '插画ID: xxxxxx\n' + '画师: xxxxx\n' + '画师ID: xxxxxxx\n' + '直链: https://pixivel.moe/detail?id=xxxxxx', atType: 0, atUid: '', atTinyId: '', atNtUid: '' } } ] ]

2024/9/30 23:16:56 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/generateMsgUniqueId ["nodeIKernelMsgService/generateMsgUniqueId",{"chatType":1}] 

2024/9/30 23:16:56 [error] xxx(xxx) | onebot 生成转发消息节点失败 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/generateMsgUniqueId, nodeIKernelMsgService/generateMsgUniqueId,[object Object]

2024/9/30 23:17:01 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/getRichMediaFilePathForGuild ["nodeIKernelMsgService/getRichMediaFilePathForGuild",{"path_info":{"md5HexStr":"xxxxxxxxx","fileName":"xxxxx.jpg","elementType":2,"elementSubType":0,"thumbSize":0,"needCreate":true,"downloadType":1,"file_uuid":""}}] 

2024/9/30 23:17:01 [error] xxx(xxx) | onebot 生成转发消息节点失败 ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/getRichMediaFilePathForGuild, nodeIKernelMsgService/getRichMediaFilePathForGuild,[object Object]

2024/9/30 23:17:01 [error] xxx(xxx) | onebot 发生错误 Error: 转发消息失败，节点为空 at SendGroupForwardMsg.handleForwardNode (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:360:62871) at async SendGroupForwardMsg._handle (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:360:61122) at async SendGroupForwardMsg.websocketHandle (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:360:51917) at async OB11WebSocket.handleAction (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:21:24219)

2024/9/30 23:17:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:18:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:19:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:20:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:21:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:22:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:23:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:24:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event

2024/9/30 23:25:10 [info] xxx(xxx) | onebot WebSocket 事件上报  meta_event
```

### OneBot 客户端运行日志

```shell
[INFO] [bot] 收到群(xxx)消息 [xx]xxx : [CQ:file,file=xxx,url=file:///C:/Program%20Files/Tencent/QQNT,file_id=/xxx,path=,file_size=xxx]
[ERROR] [api] 调用 send_private_msg 时出现错误, 返回值: 1200 , 信息:  解释: ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelMsgService/getRichMediaFilePathForGuild, nodeIKernelMsgService/getRichMediaFilePathForGuild,[object Object]
[ERROR] [api] 调用 get_group_member_info 时出现错误, 返回值: 1200 , 信息:  解释: ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo, nodeIKernelProfileService/getUserDetailInfoWithBizInfo,[object Object],
[ERROR] [api] 调用 get_stranger_info 时出现错误, 返回值: 1200 , 信息:  解释: ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoByUin, nodeIKernelProfileService/getUserDetailInfoByUin,[object Object],
[ERROR] [api] 调用 get_group_member_info 时出现错误, 返回值: 1200 , 信息:  解释: ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoWithBizInfo, nodeIKernelProfileService/getUserDetailInfoWithBizInfo,[object Object],
[ERROR] [api] 调用 get_stranger_info 时出现错误, 返回值: 1200 , 信息:  解释: ntqq api timeout IPC_UP_2, ns-ntApi-2, nodeIKernelProfileService/getUserDetailInfoByUin, nodeIKernelProfileService/getUserDetailInfoByUin,[object Object],
[ERROR] [api] 调用 send_group_forward_msg 时出现错误, 返回值: 1200 , 信息:  解释: Error: 转发消息失败，节点为空
    at SendGroupForwardMsg.handleForwardNode (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:360:62871)
    at async SendGroupForwardMsg._handle (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:360:61122)
    at async SendGroupForwardMsg.websocketHandle (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:360:51917)
    at async OB11WebSocket.handleAction (C:\Users\Administrator\Documents\Work\LiteLoaderQQNT\plugins\LLOneBot\main\main.cjs:21:24219)
[WARNING] [file]连接md5验证服务器失败: dial tcp xxx.xxx.xxx.xxx:xxxxx: i/o timeout
[INFO] [file]md5无变化
```

**Comment by idranme** [comment]
v4.0.9 是否依然存在该问题？
