### ISSUE TITLE
[BUG] get_group_member_info API报错无法获取群成员信息

### ISSUE THREAD

**Issue by ACaiCat** [LLOneBot/LLOneBot#482]
### 系统版本

Win Server 2019

### QQNT 版本

9.9.12-25765

### LLOneBot 版本

4.0.13

### OneBot 客户端

NoneBot 2

### 发生了什么?

get_group_member_info API报错无法获取群成员信息

### 如何复现

调用get_group_member_info

### 期望的结果?

返回群成员信息

### LLOneBot 运行日志

```shell
貌似没有记录相关日志
```

### OneBot 客户端运行日志

```shell
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='Error: 无法获取用户信息\n    at GetGroupMemberInfo._handle (C:\\
Users\\cai\\Documents\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:359:57426)\n    at async GetGroupMemberInfo.websocketHandle (C:\\Users\\cai\\Documents\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:359:51712)\n    at async OB11WebSocketReverse.handleAction (C:\\Users\\cai\\Documents\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:20:25448)', wording='Error: 无法获取用户信息\n    at GetGroupMemberInfo._handle (C:\\Users\\cai\\Documents\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:359:57426)\n    at async GetGroupM
emberInfo.websocketHandle (C:\\Users\\cai\\Documents\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:359:51712)\n    at async OB11WebSocketReverse.handleAction (C:\\Users\\cai\\Documents\\LiteloaderQQNT\\plugins\\LLOneBot\\main\\main.cjs:20:25448)', echo='3')
```

**Comment by idranme** [comment]
临时解决办法：更新 QQ 至最新版

https://im.qq.com/pcqq/index.shtml

**Comment by ACaiCat** [comment]
感谢!
更新到QQv9.9.15后解决
