### ISSUE TITLE
[BUG] 如果拉群邀请需要机器人同意，则会在同意进群之前就提前上报[notice.group_increase.invite]

### ISSUE THREAD

**Issue by ShoulderDorry** [LLOneBot/LLOneBot#487]
### 系统版本

 Windows Server 2016

### QQNT 版本

9.9.15-27597

### LLOneBot 版本

4.1.0

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

此前提到的初次拉群不上报[notice.group_increase.invite]已被修复，但目前如果机器人收到的拉群邀请需要机器人同意，那么group_increase.invite将会在接收到拉群邀请的那一刻立即被上报，而不是同意入群之后上报，这导致一些依赖group_increase.invite上报的插件在入群之前就试图发送消息，进而抛出错误。

### 如何复现

1.向机器人发送拉群邀请。
2.机器人收到拉群邀请后，日志立刻出现了[notice.group_increase.invite]的上报。
3.由于group_increase.invite被提前上报，引发了一系列问题。

### 期望的结果?

[notice.group_increase.invite]应该在入群之后才被上报

### OneBot 客户端运行日志

```shell
10-25 13:23:09 [SUCCESS] nonebot | OneBot V11 *** | [notice.group_increase.invite]: {'time': 1729833789, 'self_id
': ***, 'post_type': 'notice', 'notice_type': 'group_increase', 'sub_type': 'invite', 'user_id': ***, 'gro
up_id': 345542783, 'operator_id': ***}
10-25 13:23:09 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=src.plugins.otto, lineno=46)
10-25 13:23:09 [SUCCESS] nonebot | OneBot V11 *** | [message.private.friend]: Message 2090675049 from ***
'[json:data={"app":"com.tencent.qun.invite","config":{"autosize":0,"ctime":1729...]'
10-25 13:23:09 [INFO] nonebot | Matcher(type='notice', module=src.plugins.otto, lineno=46) running complete
10-25 13:23:09 [ERROR] nonebot | Running Matcher(type='notice', module=src.plugins.otto, lineno=46) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn
_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bo
otstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Python\py310\lib\site-packages\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "E:\Python\py310\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\Python\py310\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\Python\py310\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "E:\Python\py310\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt
il_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_
forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for
ever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o
nce
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Python\py310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\Python\py310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\Python\py310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\Python\py310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\Python\py310\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\pockybot\pockybot\src\plugins\welcome.py", line 58, in GroupNewMember
    await bot.send_group_msg(group_id=event.group_id, message=Message(
  File "E:\Python\py310\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\Python\py310\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\Python\py310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "E:\Python\py310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='ntqq
 api call failed, nodeIKernelMsgService/sendMsg, {"result":-1,"errMsg":"rich media transfer failed"}', wording='ntqq api
 call failed, nodeIKernelMsgService/sendMsg, {"result":-1,"errMsg":"rich media transfer failed"}', echo='41148')
10-25 13:23:10 [SUCCESS] nonebot | OneBot V11 *** | [request.group.invite]: {'time': 1729833790, 'self_id': ***, 'post_type': 'request', 'request_type': 'group', 'sub_type': 'invite', 'group_id': ***, 'user_id': ***
24, 'comment': '', 'flag': '345542783|1729833751870265|1'}
```

**Comment by idranme** [comment]
v4.1.1 已修复

**Comment by ShoulderDorry** [comment]
> v4.1.1 已修复

4.1.1中该问题确实已经修复，但是取而代之再次出现了初次拉群不上报[notice.group_increase.invite]的问题

**Comment by ShoulderDorry** [comment]
> v4.1.1 已修复

现在似乎是只有第二次同意拉群邀请或初次主动进群会上报group_increase，初次同意拉群邀请进群不上报
