### ISSUE TITLE
[BUG] 无法获取登入账号信息

### ISSUE THREAD

**Issue by Fish-LP** [LLOneBot/LLOneBot#496]
### 系统版本

macos monterey 12.7.6

### QQNT 版本

6.9.58-28971(官网和苹果商店都是这个版本)

### LLOneBot 版本

v4.1.2

### OneBot 客户端

2.16.0, built on 2023-10-20 06:28:10

### 发生了什么?

没有返回登入账号信息 

### 如何复现

1

### 期望的结果?

返回登入账号信息

### LLOneBot 运行日志

```shell
10/30/2024, 8:02:47 PM [info] (<botqq>) | onebot ws connect /
10/30/2024, 8:02:47 PM [info] (<botqq>) | onebot WebSocket 事件上报  meta_event
10/30/2024, 8:02:47 PM [info] (<botqq>) | onebot 收到正向 Websocket 消息 { action: 'get_version_info', echo: 0 }
10/30/2024, 8:02:47 PM [info] (<botqq>) | onebot 收到正向 Websocket 消息 { action: 'get_login_info', echo: 1 }
10/30/2024, 8:02:52 PM ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo [ { uids: [ 'u_BnqTAx_6_BweXUVubWAWHw' ], force: true } ] 
10/30/2024, 8:02:52 PM [info] (<botqq>) | onebot 收到正向 Websocket 消息 { action: 'get_friend_list', echo: 2 }
10/30/2024, 8:02:58 PM [error] (<botqq>) | onebot 发生错误 ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]
10/30/2024, 8:02:58 PM ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList [ false ] 
10/30/2024, 8:03:01 PM [info] (<botqq>) | onebot 有一个 Websocket 连接断开
10/30/2024, 8:03:06 PM [info] (<botqq>) | onebot WebSocket 事件上报  meta_event
10/30/2024, 8:03:25 PM 查询 LLOneBot 错误信息 没有找到 FFmpeg, 音频只能发送 WAV 和 SILK, 视频尺寸可能异常 
10/30/2024, 8:03:25 PM FFmpeg is not installed or not found in PATH: Error: Cannot find ffmpeg
    at /Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:12:20214
    at FfmpegCommand._getFfmpegPath (/Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:12:26391)
    at FfmpegCommand._spawnFfmpeg (/Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:12:20139)
    at FfmpegCommand.<anonymous> (/Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:13:1897)
    at Function.<anonymous> (/Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:14:7749)
    at /Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:14:13980
    at new Promise (<anonymous>)
    at checkFfmpeg (/Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:14:13892)
    at /Users/fish/Library/Containers/com.tencent.qq/Data/Documents/LiteLoader/plugins/LLOneBot/main/main.cjs:366:124630
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82871) 
10/30/2024, 8:03:25 PM 开始检查 FFmpeg  
10/30/2024, 8:03:27 PM LLOneBot latest version 4.1.2 
10/30/2024, 8:04:06 PM [info] (<botqq>) | onebot WebSocket 事件上报  meta_event
```

### OneBot 客户端运行日志

```shell
2024-10-30 20:02:47 I/Onebot: Overflow v1.0.0.520 正在运行
2024-10-30 20:02:47 I/Onebot: 连接到 WebSocket: ws://127.0.0.1:3001
2024-10-30 20:02:47 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-10-30 20:02:47 I/Onebot: 协议端版本信息
{
  "app_name": "LLOneBot",
  "protocol_version": "v11",
  "app_version": "4.1.2"
}
2024-10-30 20:02:58 W/Onebot: 请求失败: [get_friend_list] 请求失败: app=LLOneBot v4.1.2, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-10-30 20:02:58 E/main: Exception in coroutine MiraiConsoleImplementationTerminal
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault, parameter <this>
	at kotlin.collections.CollectionsKt__IterablesKt.collectionSizeOrDefault(Iterables.kt)
	at top.mrxiaom.overflow.internal.contact.BotWrapper.updateContacts(BotWrapper.kt:290)
	at top.mrxiaom.overflow.internal.contact.BotWrapper$updateContacts$1.invokeSuspend(BotWrapper.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by idranme** [comment]
重启 QQ

**Comment by khjxiaogu** [comment]
遇到相同问题，多次重启QQ均无效

**Comment by Fish-LP** [comment]
我暂时换插件解决了
https://github.com/NapNeko/NapCatQQ/releases/

**Comment by sansui-orz** [comment]
同样问题，更新到最新版本的QQ后，与ipc通信基本全部超时，不会调回调了，所以啥也干不了。多次重启，以及重新安装LiteLoader均无效。
目前只能看看安装旧版本QQ了。
QQ版本：9.9.16-28971

**Comment by idranme** [comment]
v4.1.4 已修复
