### ISSUE TITLE
[BUG] 4.1.4依旧遇到ipc服务器超时

### ISSUE THREAD

**Issue by fsqhn** [LLOneBot/LLOneBot#507]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.16-29804

### LLOneBot 版本

1.2.3

### OneBot 客户端

trss-yunzai

### 发生了什么?

因为最近的事打算换用LLonebot，结果配置完后连不上，看了下，基本报错为：ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelMsgListener/onRecvSysMsg

### 如何复现

就普通连就没连上，报错都是这个

### 期望的结果?

正常连上

### LLOneBot 运行日志

```shell
2024/11/21 15:42:33 process pid 7124 

2024/11/21 15:42:33 start hook 

2024/11/21 15:42:33 [info] (2377510578) | app LLOneBot/4.1.4

2024/11/21 15:42:33 [info] (2377510578) | onebot WebSocket server started 0.0.0.0:2536

2024/11/21 15:42:33 [info] (2377510578) | onebot Trying to connect to the websocket server: ws://我另一个服务器:2536/OneBotv11

2024/11/21 15:42:33 [info] (2377510578) | satori server started 0.0.0.0:5600

2024/11/21 15:42:33 [info] (2377510578) | onebot Connected to the websocket server: ws://我另一个服务器:2536/OneBotv11

2024/11/21 15:42:33 [info] (2377510578) | onebot WebSocket 事件上报 ws://我另一个服务器:2536/OneBotv11 meta_event

2024/11/21 15:42:33 [info] (2377510578) | onebot 收到反向 Websocket 消息 { action: '_set_model_show', params: { model: 'TRSS Yunzai ', model_show: 'TRSS Yunzai ' }, echo: '01JD6TRFCR4T9VSS6P751CCNGY' }

2024/11/21 15:42:33 [info] (2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_login_info', params: {}, echo: '01JD6TRFCRCCY0KC8NH390TAPF' }

2024/11/21 15:42:38 [info] (2377510578) | app 好友列表变动 76

2024/11/21 15:42:38 [info] (2377510578) | app 好友列表变动 76

2024/11/21 15:42:38 [info] 盆地(2377510578) | app 好友列表变动 76

2024/11/21 15:42:38 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_guild_service_profile', params: {}, echo: '01JD6TRKW0FVDFY8F31C6W4SND' }

2024/11/21 15:42:38 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_version_info', params: {}, echo: '01JD6TRKZCMZY1ZZV4NSCWYR54' }

2024/11/21 15:42:38 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_cookies', params: { domain: 'aq.qq.com' }, echo: '01JD6TRM118HPESPMB7ZGX7B5D' }

2024/11/21 15:42:38 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_online_clients', params: {}, echo: '01JD6TRKXPAERZCJPD7E8TXVHY' }

2024/11/21 15:42:39 ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelMsgListener/onRecvSysMsg [] 

2024/11/21 15:42:43 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: 'u_pjRTKkzi9w0KqoP6k1RtrQ', chatType: 1 }, cnt: 1 } ] 
↑这段重复了很多次，每次就peerUid有变化，其他一样
2024/11/21 15:42:43 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: 'u_TLZ0VX6T2B9nC5gT9IPtIA', chatType: 1 }, cnt: 1 } ] 

2024/11/21 15:42:43 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelTicketService/forceFetchClientKey [ { url: '' } ] 

2024/11/21 15:42:43 [error] 盆地(2377510578) | onebot 发生错误 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelTicketService/forceFetchClientKey, [{"url":""}]

2024/11/21 15:42:43 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: 'u_6SoS8y-YDrZUWq93DvcJwA', chatType: 1 }, cnt: 1 } ] 

2024/11/21 15:42:43 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_csrf_token', params: {}, echo: '01JD6TRS18S5M7M36DZ4ZX4RGW' }

2024/11/21 15:42:43 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_friend_list', params: {}, echo: '01JD6TRS2N2XQ358RKYSN9T0YH' }

2024/11/21 15:42:43 [info] 盆地(2377510578) | onebot 收到反向 Websocket 消息 { action: 'get_group_list', params: {}, echo: '01JD6TRS2NY57Z992K64DQ6D4F' }

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '322616026', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '754690153', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: 'u_P6tm94-G7x9iHrie5mm5QA', chatType: 1 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '296461580', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '585272923', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '376116729', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '630313706', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '256471375', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '904754853', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '1021208012', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '213583381', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '616255210', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '302872539', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: 'u_pjRTKkzi9w0KqoP6k1RtrQ', chatType: 1 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '805388544', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '783742324', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '867668828', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '569133797', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: 'u_5A6-EgdkqQU3xY4IZvt95Q', chatType: 1 }, cnt: 1 } ] 

2024/11/21 15:42:45 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '471019835', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:42:48 ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelGroupListener/onMemberInfoChange [] 

2024/11/21 15:42:48 [error] 盆地(2377510578) | onebot handling incoming messages ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelGroupListener/onMemberInfoChange, []

2024/11/21 15:42:48 ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList [ false ] 

2024/11/21 15:42:48 [error] 盆地(2377510578) | onebot 发生错误 ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]

2024/11/21 15:42:48 [error] 盆地(2377510578) | onebot 发生错误 ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []

2024/11/21 15:42:48 ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList [] 

2024/11/21 15:43:06 开始检查 FFmpeg C:\ntqq\ffmpeg\bin\ffmpeg.exe 

2024/11/21 15:43:08 FFmpeg is installed. 

2024/11/21 15:43:08 查询 LLOneBot 错误信息  

2024/11/21 15:43:09 LLOneBot latest version 4.1.4 

2024/11/21 15:43:12 [info] 盆地(2377510578) | app 激活的聊天窗口被删除，准备重新激活 471019835

2024/11/21 15:43:18 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelMsgService/getAioFirstViewLatestMsgsAndAddActiveChat [ { peer: { peerUid: '471019835', chatType: 2 }, cnt: 1 } ] 

2024/11/21 15:43:30 ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelGroupListener/onMemberInfoChange [] 

2024/11/21 15:43:30 [error] 盆地(2377510578) | onebot handling incoming messages ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelGroupListener/onMemberInfoChange, []

2024/11/21 15:43:30 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo [ { uids: [ 'u_5A6-EgdkqQU3xY4IZvt95Q' ], force: true } ] 

2024/11/21 15:43:30 [error] 盆地(2377510578) | satori ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo, [{"uids":["u_5A6-EgdkqQU3xY4IZvt95Q"],"force":true}]

2024/11/21 15:43:33 [info] 盆地(2377510578) | onebot WebSocket 事件上报 ws://我另一个服务器:2536/OneBotv11 meta_event

2024/11/21 15:43:34 ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelGroupListener/onMemberInfoChange [] 

2024/11/21 15:43:34 [error] 盆地(2377510578) | onebot handling incoming messages ntqq api timeout IPC_UP_3, ns-ntApi-3-register, nodeIKernelGroupListener/onMemberInfoChange, []

2024/11/21 15:43:34 ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo [ { uids: [ 'u_5A6-EgdkqQU3xY4IZvt95Q' ], force: true } ] 

2024/11/21 15:43:34 [error] 盆地(2377510578) | satori ntqq api timeout IPC_UP_3, ns-ntApi-3, nodeIKernelProfileService/getUserSimpleInfo, [{"uids":["u_5A6-EgdkqQU3xY4IZvt95Q"],"force":true}]
```

### OneBot 客户端运行日志

```shell
'    at async file:///root/TRSS_AllBot/TRSS-Yunzai/lib/plugins/loader.js:93:11\n' +   15:04:58 [89/304]
  }
}
[15:05:17.027][ERRO][unhandled.] Error
    at OneBotv11Adapter.sendApi (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:21:19)
    at Object.sendApi (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:711:41)
    at OneBotv11Adapter.getGroupArray (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:243:35)
    at OneBotv11Adapter.getGroupMap (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:270:32)
    at OneBotv11Adapter.getGroupMemberMap (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:304:48)
    at Object.getGroupMemberMap (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:745:37)
    at OneBotv11Adapter.connect (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:789:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  [stack]: [Getter/Setter: 'Error\n' +
    '    at OneBotv11Adapter.sendApi (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:21:19)\n' +
    '    at Object.sendApi (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:711:41)\n' +
    '    at OneBotv11Adapter.getGroupArray (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:243:35)\n' +
    '    at OneBotv11Adapter.getGroupMap (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:270:32)\n' +
    '    at OneBotv11Adapter.getGroupMemberMap (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:304:48)\n' +
    '    at Object.getGroupMemberMap (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:745:37)\n' +
    '    at OneBotv11Adapter.connect (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/adapter/OneBotv11.js:789:14)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)'],
  action: 'get_group_list',
  params: {},
  echo: '01JD6RM21JZWJBPRSR2C0YZ8Q4',
  error: {
    status: 'failed',
    retcode: 1200,
    data: null,
    message: 'ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []',
    wording: 'ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []',
    echo: '01JD6RM21JZWJBPRSR2C0YZ8Q4',
    raw: '{"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getGroupList, []","echo":"01JD6RM21JZWJBPRSR2C0YZ8Q4"}'
  }
}

不是跟上面的时间同时发生的，但也是这事，应该大差不差？
```

**Comment by linyuchen** [comment]
如果重启后依旧如此尝试降级QQ版本，NTQQ历史版本：https://bbs.pcbeta.com/viewthread-1969561-1-1.html

**Comment by idranme** [comment]
v4.4.1 是否存在该问题？

**Comment by fsqhn** [comment]
> v4.4.1 是否存在该问题？

不清楚，4.1.4重启服务器后就能正常用了。还是今天早上才发现的。
