### ISSUE TITLE
[BUG] 请求失败: [get_friend_list]

### ISSUE THREAD

**Issue by Kloping** [LLOneBot/LLOneBot#525]
### 系统版本

Win7 旗舰

### QQNT 版本

9.9.16-29725

### LLOneBot 版本

4.4.3

### OneBot 客户端

Overflow v1.0.1.535

### 发生了什么?

连接时 异常 
2024-12-19 12:55:07 I/Onebot: Overflow v1.0.1.535 正在运行
2024-12-19 12:55:07 I/Onebot: 连接到 WebSocket: ws://192.168.0.105:3001
2024-12-19 12:55:08 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-12-19 12:55:08 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-12-19 12:55:08 D/Onebot: [Recv] <-- {"time":1734584108,"self_id":291841860,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}
2024-12-19 12:55:08 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"app_name":"LLOneBot","protocol_version":"v11","app_version":"4.4.3"},"message":"","wording":"","echo":0}
2024-12-19 12:55:08 I/Onebot: 协议端版本信息
{
  "app_name": "LLOneBot",
  "protocol_version": "v11",
  "app_version": "4.4.3"
}
2024-12-19 12:55:08 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-12-19 12:55:13 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"user_id":291841860,"nickname":""},"message":"","wording":"","echo":1}
2024-12-19 12:55:14 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-12-19 12:55:19 D/Onebot: [Recv] <-- {"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
2024-12-19 12:55:19 W/Onebot: 请求失败: [get_friend_list] 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-19 12:55:19 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
	at cn.evolvefield.onebot.client.util.ActionSendRequest.send(ActionSendRequest.kt:67)
	at cn.evolvefield.onebot.client.util.ActionSendRequest$send$1.invokeSuspend(ActionSendRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### 如何复现

未知

### 期望的结果?

不报错就能链接成功

### LLOneBot 运行日志

```shell
2024-12-19 12:55:07 I/Onebot: Overflow v1.0.1.535 正在运行
2024-12-19 12:55:07 I/Onebot: 连接到 WebSocket: ws://192.168.0.105:3001
2024-12-19 12:55:08 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-12-19 12:55:08 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-12-19 12:55:08 D/Onebot: [Recv] <-- {"time":1734584108,"self_id":291841860,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}
2024-12-19 12:55:08 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"app_name":"LLOneBot","protocol_version":"v11","app_version":"4.4.3"},"message":"","wording":"","echo":0}
2024-12-19 12:55:08 I/Onebot: 协议端版本信息
{
  "app_name": "LLOneBot",
  "protocol_version": "v11",
  "app_version": "4.4.3"
}
2024-12-19 12:55:08 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-12-19 12:55:13 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"user_id":291841860,"nickname":""},"message":"","wording":"","echo":1}
2024-12-19 12:55:14 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-12-19 12:55:19 D/Onebot: [Recv] <-- {"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
2024-12-19 12:55:19 W/Onebot: 请求失败: [get_friend_list] 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-19 12:55:19 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
	at cn.evolvefield.onebot.client.util.ActionSendRequest.send(ActionSendRequest.kt:67)
	at cn.evolvefield.onebot.client.util.ActionSendRequest$send$1.invokeSuspend(ActionSendRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### OneBot 客户端运行日志

```shell
2024-12-19 12:55:07 I/Onebot: Overflow v1.0.1.535 正在运行
2024-12-19 12:55:07 I/Onebot: 连接到 WebSocket: ws://192.168.0.105:3001
2024-12-19 12:55:08 I/Onebot: ▌ 已连接到服务器 ┈━═☆
2024-12-19 12:55:08 D/Onebot: [Send] --> {"action":"get_version_info","echo":0}
2024-12-19 12:55:08 D/Onebot: [Recv] <-- {"time":1734584108,"self_id":291841860,"post_type":"meta_event","meta_event_type":"lifecycle","sub_type":"connect"}
2024-12-19 12:55:08 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"app_name":"LLOneBot","protocol_version":"v11","app_version":"4.4.3"},"message":"","wording":"","echo":0}
2024-12-19 12:55:08 I/Onebot: 协议端版本信息
{
  "app_name": "LLOneBot",
  "protocol_version": "v11",
  "app_version": "4.4.3"
}
2024-12-19 12:55:08 D/Onebot: [Send] --> {"action":"get_login_info","echo":1}
2024-12-19 12:55:13 D/Onebot: [Recv] <-- {"status":"ok","retcode":0,"data":{"user_id":291841860,"nickname":""},"message":"","wording":"","echo":1}
2024-12-19 12:55:14 D/Onebot: [Send] --> {"action":"get_friend_list","echo":2}
2024-12-19 12:55:19 D/Onebot: [Recv] <-- {"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
2024-12-19 12:55:19 W/Onebot: 请求失败: [get_friend_list] 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}。如果你认为这是 Overflow 的问题，请带上 logs/onebot 中的日志来反馈。
2024-12-19 12:55:19 V/Onebot: Stacktrace: 
cn.evolvefield.onebot.client.util.ActionFailedException: 请求失败: app=LLOneBot v4.4.3, message=ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false], retJson={"status":"failed","retcode":1200,"data":null,"message":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","wording":"ntqq api timeout IPC_UP_3, ns-NodeStoreApi-3, getBuddyList, [false]","echo":2}
	at cn.evolvefield.onebot.client.util.ActionSendRequest.send(ActionSendRequest.kt:67)
	at cn.evolvefield.onebot.client.util.ActionSendRequest$send$1.invokeSuspend(ActionSendRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by linyuchen** [comment]
重启QQ试试

**Comment by Kloping** [comment]
> 重启QQ试试

试了 还是一样的

**Comment by Kloping** [comment]
![image](https://github.com/user-attachments/assets/67171612-9d5e-4bd5-8b88-d3eb4003454e)

**Comment by Kloping** [comment]
删除插件数据选项开启后 重启报错消失
